In [6]:
import pandas as pd

In [7]:
sales_2025 = pd.read_excel(
    "production_sales_figures_en_202512.xlsx",
    sheet_name="Sales",
    header=None
)

sales_2025.iloc[:15, :15]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,NaN,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,2.016000e+03,2.017000e+03,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03,2.022000e+03,Jan.2023,Feb.2023,Mar.2023,Apr.2023,May.2023
3,NaN,Toyota (incl. Lexus),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Worldwide sales\nCorresponding month: \nFirst ...,9.223727e+06,9.383780e+06,9.541748e+06,9.714253e+06,8.692168e+06,9.615157e+06,9.567184e+06,709870,773271,916205,800863,838478
5,NaN,NaN,NaN,3.827368e-01,1.735231e+00,1.683415e+00,1.807897e+00,-1.052150e+01,1.061863e+01,-4.989310e-01,-5.621847,10.256381,1.458865,4.865079,10.113649
6,NaN,NaN,Sales inside of Japan\nCorresponding month: \n...,1.580851e+06,1.633161e+06,1.564309e+06,1.610169e+06,1.504221e+06,1.476136e+06,1.289132e+06,130218,155840,207839,125326,116954
7,NaN,NaN,NaN,5.540004e+00,3.308977e+00,-4.215873e+00,2.931646e+00,-6.579930e+00,-1.867079e+00,-1.266848e+01,17.982079,53.213914,26.896682,21.507034,35.138196
8,NaN,NaN,Sales outside of Japan\nCorresponding month: F...,7.642876e+06,7.750619e+06,7.977439e+06,8.104084e+06,7.187947e+06,8.139021e+06,8.278052e+06,579652,617431,708366,675537,721524
9,NaN,NaN,NaN,-6.217127e-01,1.409718e+00,2.926476e+00,1.587540e+00,-1.130463e+01,1.323151e+01,1.708203e+00,-9.681139,2.969523,-4.1771,2.266545,6.904798
10,NaN,Daihatsu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,Worldwide sales,7.803840e+05,8.169970e+05,8.481820e+05,8.379900e+05,6.939770e+05,7.251800e+05,7.660910e+05,76346,71803,86205,66010,57674
12,NaN,NaN,NaN,-1.685144e+00,4.691665e+00,3.817027e+00,-1.201629e+00,-1.718553e+01,4.496259e+00,5.641496e+00,22.598879,17.156703,17.649066,8.887862,28.338414
13,NaN,NaN,Sales inside of Japan,5.870420e+05,6.309020e+05,6.468740e+05,6.589350e+05,5.924610e+05,5.727390e+05,5.761850e+05,54224,54696,67605,51942,41970
14,NaN,NaN,NaN,-3.830767e+00,7.471356e+00,2.531613e+00,1.864505e+00,-1.008810e+01,-3.328827e+00,6.016702e-01,21.747721,13.703642,18.960056,15.076323,25.268625

In [8]:
sales_2025.iloc[2,4:].tolist()

[np.float64(2017.0),
 np.float64(2018.0),
 np.float64(2019.0),
 np.float64(2020.0),
 np.float64(2021.0),
 np.float64(2022.0),
 'Jan.2023',
 'Feb.2023',
 'Mar.2023',
 'Apr.2023',
 'May.2023',
 'Jun.2023',
 'Jul.2023',
 'Aug.2023',
 'Sep.2023',
 'Oct.2023',
 'Nov.2023',
 'Dec.2023',
 np.float64(2023.0),
 'Jan.2024',
 'Feb.2024',
 'Mar.2024',
 'Apr.2024',
 'May.2024',
 'Jun.2024',
 'Jul.2024',
 'Aug.2024',
 'Sep.2024',
 'Oct.2024',
 'Nov.2024',
 'Dec.2024',
 np.float64(2024.0),
 'Jan.2025',
 'Feb.2025',
 'Mar.2025',
 'Apr.2025',
 'May.2025',
 'Jun.2025',
 'Jul.2025',
 'Aug.2025',
 'Sep.2025',
 'Oct.2025',
 'Nov.2025',
 'Dec.2025',
 'Record high',
 '2025 Cumulative Total',
 'Cumulative Total\nRecord high']

In [9]:
[(i, sales_2025.iloc[2,i]) for i in range (0, 15)]

[(0, np.float64(nan)),
 (1, nan),
 (2, nan),
 (3, np.float64(2016.0)),
 (4, np.float64(2017.0)),
 (5, np.float64(2018.0)),
 (6, np.float64(2019.0)),
 (7, np.float64(2020.0)),
 (8, np.float64(2021.0)),
 (9, np.float64(2022.0)),
 (10, 'Jan.2023'),
 (11, 'Feb.2023'),
 (12, 'Mar.2023'),
 (13, 'Apr.2023'),
 (14, 'May.2023')]

In [10]:
years = list(range(2016, 2026))

annual_sales = sales_2025.iloc[[4, 6, 8], [3, 4, 5, 6, 7, 8, 9, 27, 40, 53]].copy()

annual_sales.index = [
    "Worldwide Sales",
    "Sales Inside Japan",
    "Sales Outside Japan"
]

annual_sales.columns = years

annual_sales = annual_sales.T

annual_sales

IndexError: positional indexers are out-of-bounds

In [11]:
import numpy as np

In [12]:
year_columns = {
    int(value): i
    for i, value in enumerate(sales_2025.iloc[2])
    if pd.notna(value) and isinstance(value, (int, float, np.integer, np.floating))
    and 2016 <= 2025
}

year_columns

{2016: 3,
 2017: 4,
 2018: 5,
 2019: 6,
 2020: 7,
 2021: 8,
 2022: 9,
 2023: 22,
 2024: 35}

In [13]:
cumulative_col = sales_2025.columns[
    sales_2025.iloc[2].astype(str).str.contains(
        "2025 Cumulative Total",
        na = False
    )
][0]
cumulative_col

np.int64(49)

In [14]:
annual_columns = [
    3, 4, 5, 6, 7, 8, 9, 22, 35, 49
]

annual_sales = sales_2025.iloc[
    [4, 6, 8],
    annual_columns
].copy()

annual_sales.columns  = range(2016, 2026)

annual_sales = annual_sales.T
annual_sales

               4          6          8
2016   9223727.0  1580851.0  7642876.0
2017   9383780.0  1633161.0  7750619.0
2018   9541748.0  1564309.0  7977439.0
2019   9714253.0  1610169.0  8104084.0
2020   8692168.0  1504221.0  7187947.0
2021   9615157.0  1476136.0  8139021.0
2022   9567184.0  1289132.0  8278052.0
2023  10307395.0  1672970.0  8634425.0
2024  10159336.0  1441842.0  8717494.0
2025    10536807    1501263    9035544

In [15]:
sales_region_2025 = pd.read_excel(
    "production_sales_figures_en_202512.xlsx",
    sheet_name="Sales by country・region",
    header=None
)

print(sales_region_2025.shape)
sales_region_2025.iloc[:20, :20]

(47, 88)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,NaN,NaN,Toyota (incl. Lexus) Sales of country/region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,Jan.2023,NaN,Feb.2023,NaN,Mar.2023,NaN,Apr.2023,NaN,May.2023,NaN
3,NaN,Worldwide sales,NaN,9223727.0,9383780.0,9541748.0,9714253.0,8692168.0,9615157.0,9567184.0,709870,-5.621847,773271,10.256381,916205,1.458865,800863,4.865079,838478,10.113649
4,NaN,Sales outside of Japan,NaN,7642876.0,7750619.0,7977439.0,8104084.0,7187947.0,8139021.0,8278052.0,579652,-9.681139,617431,2.969523,708366,-4.1771,675537,2.266545,721524,6.904798
5,NaN,North America,NaN,2797542.0,2790506.0,2798221.0,2757160.0,2408072.0,2681219.0,2445348.0,158141,-12.832032,180536,-2.062516,206231,-8.11431,215977,-1.306909,220403,3.406164
6,NaN,NaN,U.S. (incl. Hawaii),2449629.0,2434516.0,2426735.0,2383348.0,2112941.0,2332262.0,2108460.0,134392,-14.848537,158709,-2.385185,176456,-9.126678,186310,0.729888,187204,6.371953
7,NaN,NaN,Canada,217792.0,224547.0,231646.0,237091.0,191419.0,225215.0,200205.0,12859,11.836841,12033,4.389694,19662,11.760359,19616,-3.459816,21736,-5.929196
8,NaN,NaN,Mexico,104955.0,105464.0,108761.0,105663.0,76577.0,91145.0,98087.0,7850,-8.689078,7503,13.133293,7461,-13.974403,7467,-21.917808,8541,-17.526072
9,NaN,NaN,Other,25166.0,25979.0,31079.0,31058.0,27135.0,32597.0,38596.0,3040,-13.118034,2291,-36.219376,2652,-33.683421,2584,-35.319149,2922,-20.834462
10,NaN,Latin America,NaN,391794.0,419028.0,441280.0,407151.0,280257.0,385246.0,474564.0,31181,12.660332,34848,7.525687,42008,6.657188,38231,-1.717268,44854,3.041581
11,NaN,NaN,Brazil,179441.0,190862.0,202843.0,217430.0,134893.0,173475.0,191653.0,11856,7.909347,13359,0.526751,17306,-1.832208,14799,-9.773198,17409,2.49632
12,NaN,NaN,Argentina,81295.0,92052.0,94110.0,54021.0,51659.0,69913.0,90068.0,5117,7.387198,6236,-0.779634,8262,25.945122,8000,20.754717,9343,11.932431
13,NaN,NaN,Other,131058.0,136114.0,144327.0,135700.0,93705.0,141858.0,192843.0,14208,19.144654,15253,18.839112,16440,8.179246,15432,-2.772177,18102,-0.52753
14,NaN,Europe,NaN,898019.0,969077.0,1005370.0,1051550.0,961699.0,1037126.0,1032159.0,88071,-17.680653,80852,2.828509,109762,35.664405,75869,-22.822062,90033,10.766221
15,NaN,NaN,U.K.,119315.0,124946.0,124843.0,130124.0,114800.0,128334.0,128005.0,10761,0.62652,5285,10.241969,23949,21.174863,8633,-4.576103,11228,22.629969
16,NaN,NaN,France,88120.0,98036.0,106136.0,118988.0,107905.0,107558.0,120740.0,10597,-8.139736,10525,15.405702,11902,39.908311,7156,-18.347786,8145,-11.061367
17,NaN,NaN,Italy,78307.0,90002.0,90517.0,96698.0,83474.0,87237.0,104717.0,8848,-21.042299,10906,35.410976,9835,81.156751,7901,-36.487138,10614,25.922411
18,NaN,NaN,Germany,76104.0,85861.0,85850.0,93802.0,86872.0,81061.0,88508.0,6778,21.035714,7334,13.301406,7737,15.840695,5741,-33.78316,7273,1.805711
19,NaN,NaN,Spain,64200.0,70977.0,79505.0,84881.0,67411.0,72561.0,90460.0,6676,-43.667201,7583,3.7772,9694,206.384324,6875,-30.089485,8980,6.221907

In [16]:
sales_region_2025.iloc[:, 1:4].to_string()

'                         1                                                                                                                             2          3\n0                      NaN                                                                                  Toyota (incl. Lexus)\u3000Sales of country/region        NaN\n1                      NaN                                                                                                                           NaN        NaN\n2                      NaN                                                                                                                           NaN     2016.0\n3          Worldwide sales                                                                                                                           NaN  9223727.0\n4   Sales outside of Japan                                                                                                                           NaN  7642876.0\n5            North America                                                                                                                           NaN  2797542.0\n6                      NaN                                                                                                           U.S. (incl. Hawaii)  2449629.0\n7                      NaN                                                                                                                        Canada   217792.0\n8                      NaN                                                                                                                        Mexico   104955.0\n9                      NaN                                                                                                                         Other    25166.0\n10           Latin America                                                                                                                           NaN   391794.0\n11                     NaN                                                                                                                        Brazil   179441.0\n12                     NaN                                                                                                                     Argentina    81295.0\n13                     NaN                                                                                                                         Other   131058.0\n14                  Europe                                                                                                                           NaN   898019.0\n15                     NaN                                                                                                                          U.K.   119315.0\n16                     NaN                                                                                                                        France    88120.0\n17                     NaN                                                                                                                         Italy    78307.0\n18                     NaN                                                                                                                       Germany    76104.0\n19                     NaN                                                                                                                         Spain    64200.0\n20                     NaN                                                                                                                         Other   471973.0\n21                    Asia                                                                                                                           NaN  2531974.0\n22                     NaN                                                                                             China (incl. Hong Kong and Macau)  1225908.0\n23                     NaN                                                                                                                     Indonesia   389241.0\n24                     NaN                                                                                                                      Thailand   245087.0\n25                     NaN                                                                                                                   Philippines   158728.0\n26                     NaN                                                                                                                        Taiwan   139040.0\n27                     NaN                                                                                                                      Malaysia    65110.0\n28                     NaN                                                                                                                      Pakistan    62216.0\n29                     NaN                                                                                                                       Vietnam    58701.0\n30                     NaN                                                                                                             Republic of Korea    19887.0\n31                     NaN                                                                                                                       India*1        NaN\n32                     NaN                                                                                                                         Other   168056.0\n33                   Japan                                                                                                                           NaN  1580851.0\n34                 Oceania                                                                                                                           NaN   256395.0\n35                     NaN                                                                                                                     Australia   218738.0\n36                     NaN                                                                                                                         Other    37657.0\n37             Middle East                                                                                                                           NaN   584389.0\n38                     NaN                                                                                                                         GCC*2   511711.0\n39                     NaN                                                                                                                         Other    72678.0\n40                  Africa                                                                                                                           NaN   180994.0\n41                     NaN                                                                                                                  South Africa   114014.0\n42                     NaN                                                                                                                         Other    66980.0\n43                  Others                                                                                                                           NaN     1769.0\n44                     NaN                                                                                                                           NaN        NaN\n45                     NaN                                                                              *1\u3000 India was included in Asia Other  until 2021        NaN\n46                     NaN  *2\u3000GCC (Gulf Cooperation Council) consists of Saudi Arabia, the United Arab Emirates (UAE), Bahrain, Oman, Qatar and Kuwait.        NaN'

In [17]:
region_year_columns = {
    int(value): i 
    for i, value in enumerate(sales_region_2025.iloc[2])
    if pd.notna(value)
    and isinstance(value, (int, float,np.integer, np.floating))
    and 2016 <= int(value) <= 2025
}

region_year_columns

{2016: 3,
 2017: 4,
 2018: 5,
 2019: 6,
 2020: 7,
 2021: 8,
 2022: 9,
 2023: 34,
 2024: 59}

In [18]:
cumulative_col = sales_region_2025.columns[
    sales_region_2025.iloc[2].astype(str).str.contains(
        "2025 Cumulative Total",
        na=False
    )
][0]

cumulative_col

np.int64(85)

In [19]:
# Columns containing annual sales data
annual_columns = {
    **region_year_columns,
    2025: cumulative_col
}

# Regional rows from Toyota's hierarchy
regional_rows = {
    "North America": 5,
    "Latin America": 10,
    "Europe": 14,
    "Asia": 21,
    "Japan": 33,
    "Oceania": 34,
    "Middle East": 37,
    "Africa": 40,
    "Others": 43
}

# Build clean regional dataset
region_records = []

for region, row in regional_rows.items():
    for year, col in annual_columns.items():
        region_records.append({
            "Year": year,
            "Region": region,
            "Sales": sales_region_2025.iloc[row, col]
        })

regional_sales_2025 = pd.DataFrame(region_records)

regional_sales_2025.head(15)

    Year         Region      Sales
0   2016  North America  2797542.0
1   2017  North America  2790506.0
2   2018  North America  2798221.0
3   2019  North America  2757160.0
4   2020  North America  2408072.0
5   2021  North America  2681219.0
6   2022  North America  2445348.0
7   2023  North America  2617033.0
8   2024  North America  2729987.0
9   2025  North America    2929660
10  2016  Latin America   391794.0
11  2017  Latin America   419028.0
12  2018  Latin America   441280.0
13  2019  Latin America   407151.0
14  2020  Latin America   280257.0

In [20]:
regional_sales_2025["Sales"] = pd.to_numeric(
    regional_sales_2025["Sales"],
    errors="coerce"
)

In [21]:
regional_check = (
    regional_sales_2025
    .groupby("Year")["Sales"]
    .sum()
    .reset_index(name="Regional_Total")
)

worldwide = pd.DataFrame({
    "Year": list(annual_columns.keys()),
    "Worldwide_Sales": [
        sales_region_2025.iloc[3, col]
        for col in annual_columns.values()
    ]
})

worldwide["Worldwide_Sales"] = pd.to_numeric(
    worldwide["Worldwide_Sales"],
    errors="coerce"
)

validation = regional_check.merge(worldwide, on="Year")

validation["Difference"] = (
    validation["Worldwide_Sales"] - validation["Regional_Total"]
)

validation

   Year  Regional_Total  Worldwide_Sales  Difference
0  2016       9223727.0        9223727.0         0.0
1  2017       9383780.0        9383780.0         0.0
2  2018       9541748.0        9541748.0         0.0
3  2019       9714253.0        9714253.0         0.0
4  2020       8692168.0        8692168.0         0.0
5  2021       9615157.0        9615157.0         0.0
6  2022       9567184.0        9567184.0         0.0
7  2023      10307395.0       10307395.0         0.0
8  2024      10159336.0       10159336.0         0.0
9  2025      10536807.0       10536807.0         0.0

In [22]:
regional_sales_2025.dtypes
regional_sales_2025

    Year         Region      Sales
0   2016  North America  2797542.0
1   2017  North America  2790506.0
2   2018  North America  2798221.0
3   2019  North America  2757160.0
4   2020  North America  2408072.0
..   ...            ...        ...
85  2021         Others     2072.0
86  2022         Others        0.0
87  2023         Others        0.0
88  2024         Others        0.0
89  2025         Others        NaN

[90 rows x 3 columns]

In [23]:
regional_sales_2025.dtypes

Year        int64
Region     object
Sales     float64
dtype: object

In [26]:
electrified_2025 = pd.read_excel(
    "production_sales_figures_en_202512.xlsx",
    sheet_name = "Sales of Electrified vehicle",
    header  = None
    
)

print(electrified_2025.shape)
electrified_2025.iloc[:,:6].to_string()

(55, 50)

'     0                                               1                         2                         3            4            5\n0  NaN  Toyota (incl. Lexus)\u3000Electrified vehicle sales                       NaN                       NaN          NaN          NaN\n1  NaN                                             NaN                       NaN                       NaN          NaN          NaN\n2  NaN                                             NaN                       NaN                       NaN         2016         2017\n3  NaN                                           \u3000\u3000HEV                       NaN                       NaN          NaN          NaN\n4  NaN                                             NaN           Worldwide sales                       NaN      1397777      1466922\n5  NaN                                             NaN                       NaN                       NaN    16.727322     4.946783\n6  NaN                                             NaN   Sales inside of \\nJapan                       NaN       677551       631095\n7  NaN                                             NaN                       NaN                       NaN     7.232209    -6.856458\n8  NaN                                             NaN  Sales outside of \\nJapan                       NaN       720226       835827\n9  NaN                                             NaN                       NaN                       NaN    27.334349    16.050656\n10 NaN                                          \u3000\u3000MHEV                       NaN                       NaN          NaN          NaN\n11 NaN                                             NaN           Worldwide sales                       NaN            0            0\n12 NaN                                             NaN                       NaN                       NaN          NaN          NaN\n13 NaN                                             NaN   Sales inside of \\nJapan                       NaN            0            0\n14 NaN                                             NaN                       NaN                       NaN          NaN          NaN\n15 NaN                                             NaN  Sales outside of \\nJapan                       NaN            0            0\n16 NaN                                             NaN                       NaN                       NaN          NaN          NaN\n17 NaN                                          \u3000\u3000PHEV                       NaN                       NaN          NaN          NaN\n18 NaN                                             NaN           Worldwide sales                       NaN         2866        51006\n19 NaN                                             NaN                       NaN                       NaN   -55.955125  1679.692952\n20 NaN                                             NaN   Sales inside of \\nJapan                       NaN          160        26734\n21 NaN                                             NaN                       NaN                       NaN   -88.095238     16608.75\n22 NaN                                             NaN  Sales outside of \\nJapan                       NaN         2706        24272\n23 NaN                                             NaN                       NaN                       NaN   -47.588611   796.969697\n24 NaN                                          \u3000\u3000FCEV                       NaN                       NaN          NaN          NaN\n25 NaN                                             NaN           Worldwide sales                       NaN         2046         2739\n26 NaN                                             NaN                       NaN                       NaN   303.550296    33.870968\n27 NaN                                             NaN   Sales inside of \\nJapan                       NaN          950          766\n28 NaN                                             NaN                       NaN                       NaN   130.582524   -19.368421\n29 NaN                                             NaN  Sales outside of \\nJapan                       NaN         1096         1973\n30 NaN                                             NaN                       NaN                       NaN  1053.684211    80.018248\n31 NaN                                           \u3000\u3000BEV                       NaN                       NaN          NaN          NaN\n32 NaN                                             NaN           Worldwide sales                       NaN            4            0\n33 NaN                                             NaN                       NaN                       NaN   -77.777778         -100\n34 NaN                                             NaN   Sales inside of \\nJapan                       NaN            0            0\n35 NaN                                             NaN                       NaN                       NaN            －            －\n36 NaN                                             NaN  Sales outside of \\nJapan                       NaN            4            0\n37 NaN                                             NaN                       NaN                       NaN   -77.777778         -100\n38 NaN                                         \u3000\u3000Total                       NaN                       NaN          NaN          NaN\n39 NaN                                             NaN           Worldwide sales                       NaN      1402693      1520667\n40 NaN                                             NaN                       NaN                       NaN    16.453993     8.410536\n41 NaN                                             NaN   Sales inside of \\nJapan                       NaN       678661       658595\n42 NaN                                             NaN                       NaN                       NaN      7.11021    -2.956704\n43 NaN                                             NaN  Sales outside of \\nJapan                       NaN       724032       862072\n44 NaN                                             NaN                       NaN                       NaN    26.824244    19.065456\n45 NaN                                             NaN                       NaN             North America       274220       253736\n46 NaN                                             NaN                       NaN                       NaN    -3.743278    -7.469915\n47 NaN                                             NaN                       NaN                    Europe       285957       392939\n48 NaN                                             NaN                       NaN                       NaN    41.947253    37.411919\n49 NaN                                             NaN                       NaN  Asia\\n(Excluding China)         32577        36796\n50 NaN                                             NaN                       NaN                       NaN    13.552233    12.950855\n51 NaN                                             NaN                       NaN                     China       100068       139106\n52 NaN                                             NaN                       NaN                       NaN   211.408477    39.011472\n53 NaN                                             NaN                       NaN                     Other        31210        39495\n54 NaN                                             NaN                       NaN                       NaN    31.499115    26.545979'

In [28]:
electrified_year_columns  = {
    int(value) : i
    for i, value in enumerate(electrified_2025.iloc[2])
    if pd.notna(value)
    and isinstance(value, (int, float, np.integer, np.floating))
    and 2016 <= int (value) <= 2025
}

electrified_year_columns

{2016: 4,
 2017: 5,
 2018: 6,
 2019: 7,
 2020: 8,
 2021: 9,
 2022: 10,
 2023: 23,
 2024: 36}

In [29]:
electrified_cumulative_col = electrified_2025.columns[
    electrified_2025.iloc[2].astype(str).str.contains(
        "2025 Cumulative Total",
        na = False
    )
][0]
electrified_cumulative_col

np.int64(49)

In [31]:
powertrain_rows = {
    "HEV": 4,
    "MHEV": 11,
    "PHEV" : 18,
    "FCEV" : 25,
    "BEV": 32,
    "Total": 39
}
electrified_records = []

for powertrain, row in powertrain_rows.items():
    for year, col in {
        **electrified_year_columns,
        2025: electrified_cumulative_col

    }.items():
        electrified_records.append({
            "Year" : year,
            "Powertrain" : powertrain,
            "Sales": electrified_2025.iloc[row, col]
        })

electrified_sales_2025 = pd.DataFrame(electrified_records)

electrified_sales_2025["Sales"] = pd.to_numeric(
    electrified_sales_2025["Sales"],
    errors = "coerce"
)

electrified_sales_2025

    Year Powertrain      Sales
0   2016        HEV  1397777.0
1   2017        HEV  1466922.0
2   2018        HEV  1584074.0
3   2019        HEV  1860188.0
4   2020        HEV  1902621.0
5   2021        HEV  2482236.0
6   2022        HEV  2603019.0
7   2023        HEV  3420078.0
8   2024        HEV  4142412.0
9   2025        HEV  4433503.0
10  2016       MHEV        0.0
11  2017       MHEV        0.0
12  2018       MHEV        0.0
13  2019       MHEV     4602.0
14  2020       MHEV     3320.0
15  2021       MHEV     7482.0
16  2022       MHEV     4520.0
17  2023       MHEV    26859.0
18  2024       MHEV    94810.0
19  2025       MHEV   177152.0
20  2016       PHEV     2866.0
21  2017       PHEV    51006.0
22  2018       PHEV    46667.0
23  2019       PHEV    56524.0
24  2020       PHEV    48513.0
25  2021       PHEV   111882.0
26  2022       PHEV    90346.0
27  2023       PHEV   124653.0
28  2024       PHEV   153829.0
29  2025       PHEV   183845.0
30  2016       FCEV     2046.0
31  2017       FCEV     2739.0
32  2018       FCEV     2457.0
33  2019       FCEV     2494.0
34  2020       FCEV     1770.0
35  2021       FCEV     5918.0
36  2022       FCEV     3924.0
37  2023       FCEV     4023.0
38  2024       FCEV     1778.0
39  2025       FCEV     1257.0
40  2016        BEV        4.0
41  2017        BEV        0.0
42  2018        BEV        1.0
43  2019        BEV        0.0
44  2020        BEV     3346.0
45  2021        BEV    14407.0
46  2022        BEV    24466.0
47  2023        BEV   104018.0
48  2024        BEV   139892.0
49  2025        BEV   199137.0
50  2016      Total  1402693.0
51  2017      Total  1520667.0
52  2018      Total  1633199.0
53  2019      Total  1923808.0
54  2020      Total  1959570.0
55  2021      Total  2621925.0
56  2022      Total  2726275.0
57  2023      Total  3679631.0
58  2024      Total  4532721.0
59  2025      Total  4994894.0

In [32]:
regional_electrified_rows = {
    "North America": 45,
    "Europe": 47,
    "Asia (Excluding China)": 49,
    "China": 51,
    "Other": 53
}

regional_electrified_records = []
annual_columns_electrified = {
    **electrified_year_columns,
    2025: electrified_cumulative_col
}

for region, row in regional_electrified_rows.items():
    for year, col in annual_columns_electrified.items():
        regional_electrified_records.append({
            "Year": year,
            "Region": region,
            "Electrified_Sales": electrified_2025.iloc[row, col]
        })

regional_electrified_2025 = pd.DataFrame(
    regional_electrified_records
)

regional_electrified_2025["Electrified_Sales"] = pd.to_numeric(
    regional_electrified_2025["Electrified_Sales"],
    errors="coerce"
)

regional_electrified_2025

    Year                  Region  Electrified_Sales
0   2016           North America           274220.0
1   2017           North America           253736.0
2   2018           North America           248972.0
3   2019           North America           326845.0
4   2020           North America           386649.0
5   2021           North America           674446.0
6   2022           North America           578539.0
7   2023           North America           790462.0
8   2024           North America          1170401.0
9   2025           North America          1363916.0
10  2016                  Europe           285957.0
11  2017                  Europe           392939.0
12  2018                  Europe           465720.0
13  2019                  Europe           534565.0
14  2020                  Europe           507103.0
15  2021                  Europe           597989.0
16  2022                  Europe           688185.0
17  2023                  Europe           789044.0
18  2024                  Europe           864274.0
19  2025                  Europe           913797.0
20  2016  Asia (Excluding China)            32577.0
21  2017  Asia (Excluding China)            36796.0
22  2018  Asia (Excluding China)            49787.0
23  2019  Asia (Excluding China)            67375.0
24  2020  Asia (Excluding China)            70124.0
25  2021  Asia (Excluding China)            92287.0
26  2022  Asia (Excluding China)           108543.0
27  2023  Asia (Excluding China)           237512.0
28  2024  Asia (Excluding China)           354659.0
29  2025  Asia (Excluding China)           423138.0
30  2016                   China           100068.0
31  2017                   China           139106.0
32  2018                   China           199932.0
33  2019                   China           253117.0
34  2020                   China           325001.0
35  2021                   China           495959.0
36  2022                   China           554961.0
37  2023                   China           685457.0
38  2024                   China           869496.0
39  2025                   China           958733.0
40  2016                   Other            31210.0
41  2017                   Other            39495.0
42  2018                   Other            52122.0
43  2019                   Other           103349.0
44  2020                   Other           134942.0
45  2021                   Other           195640.0
46  2022                   Other           215683.0
47  2023                   Other           257536.0
48  2024                   Other           378308.0
49  2025                   Other           422943.0

In [33]:
regional_electrified_check = (
    regional_electrified_2025
    .groupby("Year")["Electrified_Sales"]
    .sum()
    .reset_index(name="Regional_Total")
)

worldwide_electrified = (
    electrified_sales_2025[
        electrified_sales_2025["Powertrain"] == "Total"
    ][["Year", "Sales"]]
    .rename(columns={"Sales": "Worldwide_Total"})
)

electrified_regional_validation = regional_electrified_check.merge(
    worldwide_electrified,
    on="Year"
)

electrified_regional_validation["Difference"] = (
    electrified_regional_validation["Worldwide_Total"]
    - electrified_regional_validation["Regional_Total"]
)

electrified_regional_validation

   Year  Regional_Total  Worldwide_Total  Difference
0  2016        724032.0        1402693.0    678661.0
1  2017        862072.0        1520667.0    658595.0
2  2018       1016533.0        1633199.0    616666.0
3  2019       1285251.0        1923808.0    638557.0
4  2020       1423819.0        1959570.0    535751.0
5  2021       2056321.0        2621925.0    565604.0
6  2022       2145911.0        2726275.0    580364.0
7  2023       2760011.0        3679631.0    919620.0
8  2024       3637138.0        4532721.0    895583.0
9  2025       4082527.0        4994894.0    912367.0

In [34]:
japan_electrified = pd.DataFrame({
    "Year": list(annual_columns_electrified.keys()),
    "Japan_Electrified": [
        electrified_2025.iloc[41, col]
        for col in annual_columns_electrified.values()
    ]
})

japan_electrified["Japan_Electrified"] = pd.to_numeric(
    japan_electrified["Japan_Electrified"],
    errors="coerce"
)

electrified_full_validation = electrified_regional_validation.merge(
    japan_electrified,
    on="Year"
)

electrified_full_validation["Calculated_Worldwide"] = (
    electrified_full_validation["Regional_Total"]
    + electrified_full_validation["Japan_Electrified"]
)

electrified_full_validation["Difference"] = (
    electrified_full_validation["Worldwide_Total"]
    - electrified_full_validation["Calculated_Worldwide"]
)

electrified_full_validation

,Year,Regional_Total,Worldwide_Total,Difference,Japan_Electrified,Calculated_Worldwide
0,2016,724032.0,1402693.0,0.0,678661.0,1402693.0
1,2017,862072.0,1520667.0,0.0,658595.0,1520667.0
2,2018,1016533.0,1633199.0,0.0,616666.0,1633199.0
3,2019,1285251.0,1923808.0,0.0,638557.0,1923808.0
4,2020,1423819.0,1959570.0,0.0,535751.0,1959570.0
5,2021,2056321.0,2621925.0,0.0,565604.0,2621925.0
6,2022,2145911.0,2726275.0,0.0,580364.0,2726275.0
7,2023,2760011.0,3679631.0,0.0,919620.0,3679631.0
8,2024,3637138.0,4532721.0,0.0,895583.0,4532721.0
9,2025,4082527.0,4994894.0,0.0,912367.0,4994894.0

In [35]:
regional_sales_2025.to_csv(
    "toyota_regional_sales_2016_2025.csv",
    index=False
)

electrified_sales_2025.to_csv(
    "toyota_electrified_sales_2016_2025.csv",
    index=False
)

regional_electrified_2025.to_csv(
    "toyota_regional_electrified_sales_2016_2025.csv",
    index=False
)

In [36]:
import os

[
    file for file in [
        "toyota_regional_sales_2016_2025.csv",
        "toyota_electrified_sales_2016_2025.csv",
        "toyota_regional_electrified_sales_2016_2025.csv"
    ]
    if os.path.exists(file)
]

['toyota_regional_sales_2016_2025.csv',
 'toyota_electrified_sales_2016_2025.csv',
 'toyota_regional_electrified_sales_2016_2025.csv']

In [1]:
import pandas as pd

In [2]:
production_2025 = pd.read_excel(
    "production_sales_figures_en_202512.xlsx",
    sheet_name = "Production",
    header = None
    
)

print(production_2025.shape)
print(production_2025.iloc[:, :8].to_string())

(31, 51)
     0                       1                                                                                                                               2             3             4             5             6             7
0  NaN              Production                                                                                                                             NaN           NaN           NaN           NaN           NaN           NaN
1  NaN                     NaN                                                                                                                             NaN           NaN           NaN           NaN           NaN           NaN
2  NaN                     NaN                                                                                                                             NaN  2.016000e+03  2.017000e+03  2.018000e+03  2.019000e+03  2.020000e+03
3  NaN  　　Toyota (incl. Lexus)                                                                                                                             NaN           NaN           NaN           NaN           NaN           NaN
4  NaN                     NaN         Worldwide production\nCorresponding month: 2 consecutive months of YoY decrease\nCY2025:  First YoY increase in 2 years  8.973988e+06  9.007511e+06  8.885573e+06  9.053517e+06  7.909488e+06
5  NaN                     NaN                                                                                                                             NaN  5.029972e-01  3.735574e-01 -1.353737e+00  1.890075e+00 -1.263629e+01
6  NaN                     NaN    Production inside of Japan\nCorresponding month:2 consecutive months of YoY decrease\nCY2025:  First YoY increase in 2 years  3.166338e+06  3.189556e+06  3.138751e+06  3.415864e+06  2.922605e+06
7  NaN                     NaN                                                                                                                             NaN -6.933162e-01  7.332761e-01 -1.592855e+00  8.828767e+00 -1.444024e+01
8  NaN                     NaN         Production outside of Japan\nCorresponding month:First YoY increase in 2 months\nCY2025:  First YoY increase in 2 years  5.807650e+06  5.817955e+06  5.746822e+06  5.637653e+06  4.986883e+06
9  NaN                     NaN                                                                                                                             NaN  1.167450e+00  1.774384e-01 -1.222646e+00 -1.899641e+00 -1.154328e+01
10 NaN              　　Daihatsu                                                                                                                             NaN           NaN           NaN           NaN           NaN           NaN
11 NaN                     NaN                                                                                                            Worldwide production  1.061373e+06  1.263249e+06  1.468819e+06  1.474430e+06  1.173632e+06
12 NaN                     NaN                                                                                                                             NaN  8.333767e+00  1.902027e+01  1.627312e+01  3.820076e-01 -2.040097e+01
13 NaN                     NaN                                                                                                      Production inside of Japan  7.228480e+05  9.193690e+05  9.312520e+05  9.535410e+05  9.106860e+05
14 NaN                     NaN                                                                                                                             NaN  3.657900e+00  2.718704e+01  1.292517e+00  2.393445e+00 -4.494301e+00
15 NaN                     NaN                                                                                                     Production outside of Japan  3.385250e+05  3.438800e+05  5.375670e+05  5.208890e+05  2.629460e+05
16 NaN                     NaN                                                                                                                             NaN  1.988066e+01  1.581862e+00  5.632401e+01 -3.102497e+00 -4.951976e+01
17 NaN                  　　Hino                                                                                                                             NaN           NaN           NaN           NaN           NaN           NaN
18 NaN                     NaN                                                                                                            Worldwide production  1.781250e+05  1.955440e+05  2.149110e+05  1.972670e+05  1.300750e+05
19 NaN                     NaN                                                                                                                             NaN  1.795603e+00  9.779088e+00  9.904165e+00 -8.209910e+00 -3.406145e+01
20 NaN                     NaN                                                                                                      Production inside of Japan  1.460000e+05  1.559320e+05  1.622400e+05  1.556500e+05  1.111930e+05
21 NaN                     NaN                                                                                                                             NaN -2.439024e+00  6.802740e+00  4.045353e+00 -4.061884e+00 -2.856216e+01
22 NaN                     NaN                                                                                                     Production outside of Japan  3.212500e+04  3.961200e+04  5.267100e+04  4.161700e+04  1.888200e+04
23 NaN                     NaN                                                                                                                             NaN  2.681088e+01  2.330584e+01  3.296728e+01 -2.098688e+01 -5.462912e+01
24 NaN                 　　Total                                                                                                                             NaN           NaN           NaN           NaN           NaN           NaN
25 NaN                     NaN               Worldwide production\nCorresponding month: First YoY increase in 2 months\nCY2025:  First YoY increase in 2 years  1.021349e+07  1.046630e+07  1.056930e+07  1.072521e+07  9.213195e+06
26 NaN                     NaN                                                                                                                             NaN  1.286253e+00  2.475335e+00  9.841010e-01  1.475130e+00 -1.409780e+01
27 NaN                     NaN         Production inside of Japan\nCorresponding month: First YoY increase in 2 months\nCY2025:  First YoY increase in 2 years  4.035186e+06  4.264857e+06  4.232243e+06  4.525055e+06  3.944484e+06
28 NaN                     NaN                                                                                                                             NaN -6.145560e-03  5.691708e+00 -7.647150e-01  6.918601e+00 -1.283014e+01
29 NaN                     NaN  Production outside of Japan\nCorresponding month::2 consecutive months of YoY decrease\nCY2025:  First YoY increase in 2 years  6.178300e+06  6.201447e+06  6.337060e+06  6.200159e+06  5.268711e+06
30 NaN                     NaN                                                                                                                             NaN  2.148537e+00  3.746500e-01  2.186796e+00 -2.160324e+00 -1.502297e+01

In [3]:
import numpy as np
production_year_columns = {
    int(value): i
    for i,value in enumerate(production_2025.iloc[2])
    if pd.notna(value)
    and isinstance (value, (int, float, np.integer, np.floating))
    and 2016 <= int(value) <= 2025
}

production_year_columns

{2016: 3,
 2017: 4,
 2018: 5,
 2019: 6,
 2020: 7,
 2021: 8,
 2022: 9,
 2023: 22,
 2024: 35}

In [4]:
production_cumulative_col = production_2025.columns[
    production_2025.iloc[2].astype(str).str.contains(
        "2025 Cumulative Total",
        na = False
    )
][0]

production_cumulative_col

np.int64(49)

In [5]:
production_rows = {
     "Worldwide": 4,
    "Inside Japan": 6,
    "Outside Japan": 8
}
production_records = []
annual_columns_production = {
    **production_year_columns,
    2025: production_cumulative_col
}

for production_type, row in production_rows.items():
    for year, col in annual_column_production.items():
        production_records.append({
            "Year": year,
            "Production_type" : production_type,
            "Production": production_2025.iloc[row, col]
        })

production_sales_2025 = pd.DataFrame(production_records)
production_sales_2025["Production"] = pd.to_numeric(
    production_sales_2025["Production"],
    errors = "coerce"

)

production_sales_2025

NameError: name 'annual_column_production' is not defined

In [6]:
production_rows = {
    "Worldwide": 4,
    "Inside Japan": 6,
    "Outside Japan": 8
}

production_records = []

annual_columns_production = {
    **production_year_columns,
    2025: production_cumulative_col
}

for production_type, row in production_rows.items():
    for year, col in annual_columns_production.items():
        production_records.append({
            "Year": year,
            "Production_Type": production_type,
            "Production": production_2025.iloc[row, col]
        })

production_sales_2025 = pd.DataFrame(production_records)

production_sales_2025["Production"] = pd.to_numeric(
    production_sales_2025["Production"],
    errors="coerce"
)

production_sales_2025

    Year Production_Type  Production
0   2016       Worldwide   8973988.0
1   2017       Worldwide   9007511.0
2   2018       Worldwide   8885573.0
3   2019       Worldwide   9053517.0
4   2020       Worldwide   7909488.0
5   2021       Worldwide   8583258.0
6   2022       Worldwide   9026713.0
7   2023       Worldwide  10033171.0
8   2024       Worldwide   9521876.0
9   2025       Worldwide   9950904.0
10  2016    Inside Japan   3166338.0
11  2017    Inside Japan   3189556.0
12  2018    Inside Japan   3138751.0
13  2019    Inside Japan   3415864.0
14  2020    Inside Japan   2922605.0
15  2021    Inside Japan   2877962.0
16  2022    Inside Japan   2656009.0
17  2023    Inside Japan   3370752.0
18  2024    Inside Japan   3128351.0
19  2025    Inside Japan   3275628.0
20  2016   Outside Japan   5807650.0
21  2017   Outside Japan   5817955.0
22  2018   Outside Japan   5746822.0
23  2019   Outside Japan   5637653.0
24  2020   Outside Japan   4986883.0
25  2021   Outside Japan   5705296.0
26  2022   Outside Japan   6370704.0
27  2023   Outside Japan   6662419.0
28  2024   Outside Japan   6393525.0
29  2025   Outside Japan   6675276.0

In [7]:
production_check = (
    production_sales_2025[
        production_sales_2025["Production_Type"] != "Worldwide"
    ]
    .groupby("Year")["Production"]
    .sum()
    .reset_index(name = "Calculated_Worldwide")
)

reported_production = (
     production_sales_2025[
        production_sales_2025["Production_Type"] == "Worldwide"
    ][["Year", "Production"]]
    .rename(columns={"Production": "Reported_Worldwide"})
)

production_validation = production_check.merge(
    reported_production,
    on = "Year"
)

production_validation["Difference"] = (
    production_validation["Reported_Worldwide"]
    - production_validation["Calculated_Worldwide"]
)

production_validation

   Year  Calculated_Worldwide  Reported_Worldwide  Difference
0  2016             8973988.0           8973988.0         0.0
1  2017             9007511.0           9007511.0         0.0
2  2018             8885573.0           8885573.0         0.0
3  2019             9053517.0           9053517.0         0.0
4  2020             7909488.0           7909488.0         0.0
5  2021             8583258.0           8583258.0         0.0
6  2022             9026713.0           9026713.0         0.0
7  2023            10033171.0          10033171.0         0.0
8  2024             9521876.0           9521876.0         0.0
9  2025             9950904.0           9950904.0         0.0

In [8]:
production_sales_2025.to_csv(
    "toyota_production_2016_2025.csv",
    index = False
)

In [10]:
production_region_2025 = pd.read_excel(
     "production_sales_figures_en_202512.xlsx",
    sheet_name = "Production by country・region",
    header = None

)
print(production_region_2025.shape)
print(production_region_2025.iloc[:, :6].to_string())

(39, 88)
     0                                                  1               2        3        4        5
0  NaN  Toyota (incl. Lexus)　Production of country/region             NaN      NaN      NaN      NaN
1  NaN                                                NaN             NaN      NaN      NaN      NaN
2  NaN                                                NaN             NaN     2016     2017     2018
3  NaN                               Worldwide production             NaN  8973988  9007511  8885573
4  NaN                        Production outside of Japan             NaN  5807650  5817955  5746822
5  NaN                                      North America             NaN  2124725  1983795  1928982
6  NaN                                                NaN            U.S.  1382246  1263546  1241616
7  NaN                                                NaN          Canada   601716   571535   497354
8  NaN                                                NaN          Mexico   140763   148714   190012
9  NaN                                      Latin America             NaN   274129   324035   350959
10 NaN                                                NaN          Brazil   175901   197528   209033
11 NaN                                                NaN       Argentina    97768   125317   141164
12 NaN                                                NaN       Venezuela      460     1190      762
13 NaN                                             Europe             NaN   688689   779635   773880
14 NaN                                                NaN            U.K.   180396   144070   129378
15 NaN                                                NaN          Turkey   150599   279902   257084
16 NaN                                                NaN          France   237848   233652   248537
17 NaN                                                NaN          Russia    31248    31843    39394
18 NaN                                                NaN  Czech Republic    88509    90168    99487
19 NaN                                                NaN      Kazakhstan       89        0        0
20 NaN                                               Asia             NaN  2517651  2556134  2570815
21 NaN                                                NaN       Indonesia   386516   396605   197318
22 NaN                                                NaN        Thailand   549134   523590   588939
23 NaN                                                NaN     Philippines    55039    61972    46121
24 NaN                                                NaN        Malaysia    51532    54807    48181
25 NaN                                                NaN          Taiwan   142620   117745    93752
26 NaN                                                NaN         Vietnam    50842    41445    52666
27 NaN                                                NaN           India   146503   153386   160951
28 NaN                                                NaN           China  1073372  1145414  1317009
29 NaN                                                NaN        Pakistan    62093    61170    65878
30 NaN                                                NaN         Myanmar      NaN      NaN      NaN
31 NaN                                                NaN        Cambodia      NaN      NaN      NaN
32 NaN                                              Japan             NaN  3166338  3189556  3138751
33 NaN                                          Australia             NaN    90240    60942        ―
34 NaN                                             Africa             NaN   112216   113414   122186
35 NaN                                                NaN    South Africa   110791   112997   121156
36 NaN                                                NaN           Egypt     1425      417     1030
37 NaN                                                NaN           Kenya        ―        ―        ―
38 NaN                                                NaN           Ghana      NaN      NaN      NaN

In [14]:
regional_sales_2025 = pd.read_csv(
    "toyota_regional_sales_2016_2025.csv"
)

regional_sales_2025.head()

   Year         Region      Sales
0  2016  North America  2797542.0
1  2017  North America  2790506.0
2  2018  North America  2798221.0
3  2019  North America  2757160.0
4  2020  North America  2408072.0

In [16]:
regional_sales_2025_summary = (
    regional_sales_2025[
        (regional_sales_2025["Year"] == 2025) &
        (regional_sales_2025["Sales"].notna())
    ][["Region", "Sales"]]
    .copy()
)

# Total global 2025 sales
total_global_2025_sales = regional_sales_2025_summary["Sales"].sum()

# Global share
regional_sales_2025_summary["% Global Share"] = (
    regional_sales_2025_summary["Sales"]
    / total_global_2025_sales
    * 100
)

# Rank
regional_sales_2025_summary["Rank"] = (
    regional_sales_2025_summary["Sales"]
    .rank(method="min", ascending=False)
    .astype(int)
)

regional_sales_2025_summary = (
    regional_sales_2025_summary
    .sort_values("Sales", ascending=False)
    .reset_index(drop=True)
)

regional_sales_2025_summary[
    ["Rank", "Region", "Sales", "% Global Share"]
]

   Rank         Region      Sales  % Global Share
0     1           Asia  3285605.0       31.182169
1     2  North America  2929660.0       27.804059
2     3          Japan  1501263.0       14.247798
3     4         Europe  1182551.0       11.223049
4     5    Middle East   600891.0        5.702781
5     6  Latin America   472049.0        4.480000
6     7        Oceania   300560.0        2.852477
7     8         Africa   264228.0        2.507667

In [17]:
top_3_share = (
    regional_sales_2025_summary
    .head(3)["% Global Share"]
    .sum()
)

print(f"Total global 2025 sales: {total_global_2025_sales:,.0f}")
print(f"top 3 regions combined share:{top_3_share:2f}%")

Total global 2025 sales: 10,536,807
top 3 regions combined share:73.234026%

In [2]:
import pandas as pd

In [3]:
sales_2026 = pd.read_excel(
    "production_sales_figures_2026-06.xlsx",
    sheet_name = "販売_Sales",
    header = None
)

print(sales_2026.shape)
display(sales_2026.iloc[:12, :20])

(34, 46)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,NaN,販売/Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,2017,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03,2.022000e+03,2.023000e+03,Jan.2024,Feb.2024,Mar.2024,Apr.2024,May.2024,Jun.2024,July.2024,Aug.2024,Sep.2024,Oct.2024
3,NaN,Toyota (incl. Lexus),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,グローバル販売/Worldwide sales\n単月：5ヶ月ぶりの前年超え\nCorres...,9383780,9.541748e+06,9.714253e+06,8.692168e+06,9.615157e+06,9.567184e+06,1.030740e+07,784527,719630,897251,797088,840680,853082,857969,826862,853149,903103
5,NaN,NaN,NaN,0.017352,1.683415e-02,1.807897e-02,-1.052150e-01,1.061863e-01,-4.989310e-03,7.736979e-02,0.10517,-0.069369,-0.020688,-0.004714,0.002626,-0.051021,-0.001788,-0.030966,-0.073665,0.014453
6,NaN,NaN,国内販売/Sales inside of Japan\n単月：3ヶ月連続の前年超え\nCor...,1633161,1.564309e+06,1.610169e+06,1.504221e+06,1.476136e+06,1.289132e+06,1.672970e+06,112425,103946,134374,107947,102071,121533,140353,109505,135179,143548
7,NaN,NaN,NaN,0.03309,-4.215873e-02,2.931646e-02,-6.579930e-02,-1.867079e-02,-1.266848e-01,2.977492e-01,-0.13664,-0.332995,-0.353471,-0.13867,-0.127255,-0.144363,-0.005844,-0.090686,-0.062858,0.071286
8,NaN,NaN,海外販売/Sales outside of Japan\n単月：5ヶ月連続の前年割れ\nCo...,7750619,7.977439e+06,8.104084e+06,7.187947e+06,8.139021e+06,8.278052e+06,8.634425e+06,672102,615684,762877,689141,738609,731549,717616,717357,717970,759555
9,NaN,NaN,NaN,0.014097,2.926476e-02,1.587540e-02,-1.130463e-01,1.323151e-01,1.708203e-02,4.305035e-02,0.159492,-0.002829,0.076953,0.020138,0.023679,-0.033505,-0.000991,-0.021153,-0.075672,0.004384
10,NaN,Daihatsu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,グローバル販売/Worldwide sales,816997,8.481820e+05,8.379900e+05,6.939770e+05,7.251800e+05,7.660910e+05,7.904410e+05,37344,24753,32268,29248,38068,49229,56055,51148,58678,60544

In [4]:
display(sales_2026.iloc[2, :])

0                     NaN
1                     NaN
2                     NaN
3                    2017
4                  2018.0
5                  2019.0
6                  2020.0
7                  2021.0
8                  2022.0
9                  2023.0
10               Jan.2024
11               Feb.2024
12               Mar.2024
13               Apr.2024
14               May.2024
15               Jun.2024
16              July.2024
17               Aug.2024
18               Sep.2024
19               Oct.2024
20               Nov.2024
21               Dec.2024
22                 2024.0
23               Jan.2025
24               Feb.2025
25               Mar.2025
26               Apr.2025
27               May.2025
28               Jun.2025
29              July.2025
30               Aug.2025
31               Sep.2025
32               Oct.2025
33               Nov.2025
34               Dec.2025
35                 2025.0
36       Jan.-Jun.\n 2025
37               Jan.2026
38               Feb.2026
39               Mar.2026
40               Apr.2026
41               May.2026
42               Jun.2026
43    6月過去最高\nRecord high
44       Jan.-Jun.\n 2026
45    1-6月過去最高Record high
Name: 2, dtype: object

In [9]:
h1_2026 = pd.DataFrame({
    "Metric" : [
        "Worldwide sales",
        "Sales inside Japan",
        "Sales outside_Japan"
    ],
    "H1_2025" : [
        sales_2026.iloc[4, 36],
        sales_2026.iloc[6, 36],
        sales_2026.iloc[8, 36]
    ],
    "H1_2026": [
        sales_2026.iloc[4, 44],
        sales_2026.iloc[6, 44],
        sales_2026.iloc[8, 44]
    ]
})

h1_2026["YoY_%"] = (
    (h1_2026["H1_2026"] - h1_2026["H1_2025"])
    / h1_2026["H1_2025"] * 100
)
display(h1_2026)

                Metric  H1_2025  H1_2026     YoY_%
0      Worldwide sales  5159831  5008898 -2.925154
1   Sales inside Japan   768445   804721  4.720702
2  Sales outside_Japan  4391386  4204177 -4.263096

In [10]:
sales_region_2026 = pd.read_excel(
    "production_sales_figures_2026-06.xlsx",
    sheet_name = "Sales by country or region",
    header = None
)
print(sales_region_2026.shape)
display(sales_region_2026.iloc[:15, :20])

(48, 79)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,NaN,NaN,トヨタ(含 レクサス) 国・地域別販売 / Toyota (incl. Lexus) Sal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,2017,2018,2019,2020,2021,2022.0,2023.0,Jan.2024,NaN,Feb.2024,NaN,Mar.2024,NaN,Apr.2024,NaN,May.2024,NaN
3,NaN,グローバル販売/Worldwide sales,NaN,9383780,9541748,9714253,8692168,9615157,9567184.0,10307395.0,784527,0.10517,719630,-0.069369,897251,-0.020688,797088,-0.004714,840680,0.002626
4,NaN,海外販売/Sales outside of Japan,NaN,7750619,7977439,8104084,7187947,8139021,8278052.0,8634425.0,672102,0.159492,615684,-0.002829,762877,0.076953,689141,0.020138,738609,0.023679
5,NaN,北米/North America,NaN,2790506,2798221,2757160,2408072,2681219,2445348.0,2617033.0,193327,0.222498,214189,0.186406,251243,0.21826,249945,0.157276,253321,0.149354
6,NaN,NaN,米国/U.S.,2434516,2426735,2383348,2112941,2332262,2108460.0,2248477.0,165753,0.233355,184451,0.162196,214894,0.217833,211809,0.136863,216620,0.157133
7,NaN,NaN,カナダ/Canada,224547,231646,237091,191419,225215,200205.0,227460.0,15526,0.207403,17453,0.450428,24287,0.235225,25060,0.277529,23670,0.088977
8,NaN,NaN,メキシコ/Mexico,105464,108761,105663,76577,91145,98087.0,106794.0,9493,0.209299,9808,0.30721,9300,0.246482,9998,0.338958,10112,0.183936
9,NaN,NaN,その他/Other,25979,31079,31058,27135,32597,38596.0,34302.0,2555,-0.159539,2477,0.081187,2762,0.041478,3078,0.191176,2919,-0.001027
10,NaN,中南米,NaN,419028,441280,407151,280257,385246,474564.0,478796.0,31807,0.020076,34715,-0.003817,40230,-0.042325,38423,0.005022,38946,-0.131716
11,NaN,NaN,ブラジル/Brazil,190862,202843,217430,134893,173475,191653.0,194412.0,12314,0.03863,12075,-0.096115,17033,-0.015775,15378,0.039124,15645,-0.101327
12,NaN,NaN,アルゼンチン/Argentina,92052,94110,54021,51659,69913,90068.0,87439.0,3195,-0.375611,7056,0.131495,7002,-0.152505,7097,-0.112875,6939,-0.257305
13,NaN,NaN,その他/Other,136114,144327,135700,93705,141858,192843.0,196945.0,16298,0.1471,15584,0.021701,16195,-0.014903,15948,0.033437,16362,-0.096122
14,NaN,欧州,NaN,969077,1005370,1051550,961699,1037126,1032159.0,1126107.0,89840,0.020086,92275,0.141283,127771,0.164073,90982,0.199199,96593,0.072862

In [11]:
display(sales_region_2026.iloc[2, :])

0                                               NaN
1                                               NaN
2                                               NaN
3                                              2017
4                                              2018
                          ...
74                  Reasons for single-month change
75                                 Jan.-Jun.\n 2026
76                                              NaN
77                                    2026年1-6月増減要因
78    Reasons for Jan.-Jun. cumulative total change
Name: 2, Length: 79, dtype: object

In [15]:
regional_h1_2026 = pd.DataFrame({
    "Region": [
        "North America",
        "Latin America",
        "Europe",
        "Asia",
        "Japan",
        "Oceania",
        "Middle East",
        "Africa",
        "Others"
        
    ],
    "H1_2025": [
        sales_region_2026.iloc[5,62],
        sales_region_2026.iloc[10, 62],
        sales_region_2026.iloc[14, 62],
        sales_region_2026.iloc[21, 62],
        sales_region_2026.iloc[33, 62],
        sales_region_2026.iloc[34, 62],
        sales_region_2026.iloc[37, 62],
        sales_region_2026.iloc[40, 62],
        sales_region_2026.iloc[43, 62]
    ],
    "H1_2026":[
        sales_region_2026.iloc[5,75],
        sales_region_2026.iloc[10, 75],
        sales_region_2026.iloc[14, 75],
        sales_region_2026.iloc[21, 75],
        sales_region_2026.iloc[33, 75],
        sales_region_2026.iloc[34, 75],
        sales_region_2026.iloc[37, 75],
        sales_region_2026.iloc[40, 75],
        sales_region_2026.iloc[43, 75],
    ]
})
reional_h1_2026["YoY_%"] = (
    (regional_h1_2026["H1_2026"] - regional_h1_2026["H1_2025"])
    / regional_h1_2026["H1_2025"] * 100
)
regional_h1_2026 = regional_h1_2026.sort_values(
    "H1_2026", ascending = False
).reset_index(drop = True)
display(regional_h1_2026)

TypeError: unsupported operand type(s) for -: 'int' and 'str'

In [16]:
regional_h1_2026 = pd.DataFrame({
    "Region": [
        "North America",
        "Latin America",
        "Europe",
        "Asia",
        "Japan",
        "Oceania",
        "Middle East",
        "Africa",
        "Others"
    ],
    "H1_2025": [
        sales_region_2026.iloc[5, 62],
        sales_region_2026.iloc[10, 62],
        sales_region_2026.iloc[14, 62],
        sales_region_2026.iloc[21, 62],
        sales_region_2026.iloc[33, 62],
        sales_region_2026.iloc[34, 62],
        sales_region_2026.iloc[37, 62],
        sales_region_2026.iloc[40, 62],
        sales_region_2026.iloc[43, 62]
    ],
    "H1_2026": [
        sales_region_2026.iloc[5, 75],
        sales_region_2026.iloc[10, 75],
        sales_region_2026.iloc[14, 75],
        sales_region_2026.iloc[21, 75],
        sales_region_2026.iloc[33, 75],
        sales_region_2026.iloc[34, 75],
        sales_region_2026.iloc[37, 75],
        sales_region_2026.iloc[40, 75],
        sales_region_2026.iloc[43, 75]
    ]
})

regional_h1_2026["YoY_%"] = (
    (regional_h1_2026["H1_2026"] - regional_h1_2026["H1_2025"])
    / regional_h1_2026["H1_2025"] * 100
)

regional_h1_2026 = regional_h1_2026.sort_values(
    "H1_2026", ascending=False
).reset_index(drop=True)

display(regional_h1_2026)

TypeError: unsupported operand type(s) for -: 'int' and 'str'

In [17]:
for col in range (55,79):
    print(col, "| Header:",sales_region_2026.iloc[2, col],
         "| Value:",sales_region_2026.iloc[3, col])

55 | Header: Nov.2025 | Value: 900302
56 | Header: nan | Value: -0.022015731574710817
57 | Header: Dec.2025 | Value: 930459
58 | Header: nan | Value: 0.027647759176343545
59 | Header: 2025.0 | Value: 10536807.0
60 | Header: Jan.-Jun.
 2025 | Value: 5159831
61 | Header: Jan.2026 | Value: 822577
62 | Header: nan | Value: 0.046804649540976184
63 | Header: Feb.2026 | Value: 736411
64 | Header: nan | Value: -0.03370944271166154
65 | Header: Mar.2026 | Value: 897871
66 | Header: nan | Value: -0.07287065203698306
67 | Header: Apr.2026 | Value: 849306
68 | Header: nan | Value: -0.03142790672213702
69 | Header: May.2026 | Value: 834279
70 | Header: nan | Value: -0.07170412174634844
71 | Header: Jun.2026 | Value: 868454
72 | Header: nan | Value: 0.0006325577108092784
73 | Header: 単月増減要因 | Value: 北米、日本などで需要が堅調なものの、中国での販売が減少し、全体としては前年並み
74 | Header: Reasons for single-month change | Value: Although demand remained steady in North America and Japan, sales in China decreased, resulting in overall sales that were broadly in line with the previous year.
75 | Header: Jan.-Jun.
 2026 | Value: 5008898
76 | Header: nan | Value: -0.02925153943995451
77 | Header: 2026年1-6月増減要因 | Value: 北米、日本などで需要が堅調なものの、中国での販売が減少し、全体としては前年割れ
78 | Header: Reasons for Jan.-Jun. cumulative total change | Value: Although demand remained steady in North America and Japan, sales in China declined, resulting in an overall decrease in sales compared to the previous year.

In [18]:
regional_h1_2026 = pd.DataFrame({
    "Region": [
        "North America",
        "Latin America",
        "Europe",
        "Asia",
        "Japan",
        "Oceania",
        "Middle East",
        "Africa",
        "Others"
    ],
    "H1_2025": [
        sales_region_2026.iloc[5, 60],
        sales_region_2026.iloc[10, 60],
        sales_region_2026.iloc[14, 60],
        sales_region_2026.iloc[21, 60],
        sales_region_2026.iloc[33, 60],
        sales_region_2026.iloc[34, 60],
        sales_region_2026.iloc[37, 60],
        sales_region_2026.iloc[40, 60],
        sales_region_2026.iloc[43, 60]
    ],
    "H1_2026": [
        sales_region_2026.iloc[5, 75],
        sales_region_2026.iloc[10, 75],
        sales_region_2026.iloc[14, 75],
        sales_region_2026.iloc[21, 75],
        sales_region_2026.iloc[33, 75],
        sales_region_2026.iloc[34, 75],
        sales_region_2026.iloc[37, 75],
        sales_region_2026.iloc[40, 75],
        sales_region_2026.iloc[43, 75]
    ]
})

# Make sure values are numeric
regional_h1_2026["H1_2025"] = pd.to_numeric(
    regional_h1_2026["H1_2025"], errors="coerce"
)
regional_h1_2026["H1_2026"] = pd.to_numeric(
    regional_h1_2026["H1_2026"], errors="coerce"
)

regional_h1_2026["YoY_%"] = (
    (regional_h1_2026["H1_2026"] - regional_h1_2026["H1_2025"])
    / regional_h1_2026["H1_2025"] * 100
)

regional_h1_2026 = regional_h1_2026.sort_values(
    "H1_2026", ascending=False
).reset_index(drop=True)

display(regional_h1_2026)

          Region  H1_2025  H1_2026      YoY_%
0  North America  1438981  1452343   0.928574
1           Asia  1544011  1436054  -6.991984
2          Japan   768445   804721   4.720702
3         Europe   612007   612271   0.043137
4  Latin America   244478   230384  -5.764936
5    Middle East   279254   218855 -21.628696
6         Africa   123651   131939   6.702736
7        Oceania   149004   122331 -17.900862
8         Others        0        0        NaN

In [19]:
regional_check = regional_h1_2026[
    regional_h1_2026["Region"] != "Others"
]

print("Regional H1 2026 total:",
      f"{regional_check['H1_2026'].sum():,.0f}")

print("Worldwide H1 2026:",
      f"{h1_2026.loc[0, 'H1_2026']:,.0f}")

print("Difference:",
      f"{regional_check['H1_2026'].sum() - h1_2026.loc[0, 'H1_2026']:,.0f}")

Regional H1 2026 total: 5,008,898
Worldwide H1 2026: 5,008,898
Difference: 0

In [3]:
import pandas as pd

In [4]:
electrified_2026 = pd.read_excel(
    "production_sales_figures_2026-06.xlsx",
    sheet_name="電動車_Electrified vehicle sales",
    header=None
)

print(electrified_2026.shape)
display(electrified_2026.iloc[:15, :20])

(55, 45)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,NaN,トヨタ(含 レクサス) 電動車販売 / Toyota (incl. Lexus) Elect...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,2017,2018,2019,2020,2021,2022,2023,Jan.2024,Feb.2024,Mar.2024,Apr.2024,May.2024,Jun.2024,July.2024,Aug.2024,Sep.2024
3,NaN,HEV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,グローバル販売\nWorldwide sales,NaN,1466922,1584074,1860188,1902621,2482236,2603019,3420078,301000,276922,358899,305110,330547,342545,349446,336848,366809
5,NaN,NaN,NaN,NaN,0.049468,0.079862,0.174306,0.022811,0.30464,0.048659,0.313889,0.297693,0.085828,0.149187,0.243256,0.265751,0.172573,0.224906,0.224194,0.151019
6,NaN,NaN,国内販売\nSales inside of Japan,NaN,631095,603681,628326,527995,552309,568745,892162,69098,68220,86780,64161,59157,65995,76569,61386,79379
7,NaN,NaN,NaN,NaN,-0.068565,-0.043439,0.040825,-0.15968,0.04605,0.029759,0.56865,99.945036,81.584329,81.352945,100.444604,92.203744,83.475632,99.96214,102.41583,106.894787
8,NaN,NaN,海外販売\nSales outside of Japan,NaN,835827,980393,1231862,1374626,1929927,2034274,2527916,231902,208702,272119,240949,271390,276550,272877,275462,287430
9,NaN,NaN,NaN,NaN,0.160507,0.172962,0.256498,0.115893,0.403965,0.054068,0.242662,142.433697,121.753182,132.330429,132.728675,137.769813,129.791807,130.75961,127.990298,117.595316
10,NaN,MHEV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,グローバル販売\nWorldwide sales,NaN,0,0,4602,3320,7482,4520,26859,3053,3689,4403,5825,5848,6962,7708,7196,7363
12,NaN,NaN,NaN,NaN,－,－,－,-0.278575,1.253614,-0.395883,4.942257,3.483113,10.823718,3.138158,3.412879,0.716466,1.140178,1.206068,2.02226,1.403852
13,NaN,NaN,国内販売\nSales inside of Japan,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,NaN,NaN,NaN,NaN,－,－,－,－,－,－,－,－,－,－,－,－,－,－,－,－

In [5]:
for col in range (25, 45):
    print(
        col,
        "| Header:", electrified_2026.iloc[2, col],
        "| HEV:", electrified_2026.iloc[4,col]
    
    )

25 | Header: Feb.2025 | HEV: 340081
26 | Header: Mar.2025 | HEV: 426818
27 | Header: Apr.2025 | HEV: 378976
28 | Header: May.2025 | HEV: 381202
29 | Header: Jun.2025 | HEV: 361054
30 | Header: July.2025 | HEV: 365862
31 | Header: Aug.2025 | HEV: 338031
32 | Header: Sep.2025 | HEV: 360288
33 | Header: Oct.2025 | HEV: 378378
34 | Header: Nov.2025 | HEV: 374270
35 | Header: Dec.2025 | HEV: 383599
36 | Header: 2025 | HEV: 4433503
37 | Header: Jan.-Jun.
 2025 | HEV: 2233075
38 | Header: Jan.2026 | HEV: 365499
39 | Header: Feb.2026 | HEV: 326702
40 | Header: Mar.2026 | HEV: 442544
41 | Header: Apr.2026 | HEV: 384446
42 | Header: May.2026 | HEV: 396468
43 | Header: Jun.2026 | HEV: 415218
44 | Header: Jan.-Jun.
 2026 | HEV: 2330877

In [6]:
powertrain_rows = {
    "HEV": 4,
    "MHEV": 11,
    "PHEV": 18,
    "FCEV": 25,
    "BEV": 32
}

electrified_h1_2026 = pd.DataFrame({
    "Powertrain": list(powertrain_rows.keys()),
    "H1_2025": [
        electrified_2026.iloc[row, 37]
        for row in powertrain_rows.values()
    ],
    "H1_2026": [
        electrified_2026.iloc[row, 44]
        for row in powertrain_rows.values()
    ]
})

electrified_h1_2026["H1_2025"] = pd.to_numeric(
    electrified_h1_2026["H1_2025"], errors="coerce"
)
electrified_h1_2026["H1_2026"] = pd.to_numeric(
    electrified_h1_2026["H1_2026"], errors="coerce"
)

electrified_h1_2026["YoY_%"] = (
    (electrified_h1_2026["H1_2026"] - electrified_h1_2026["H1_2025"])
    / electrified_h1_2026["H1_2025"] * 100
)

display(electrified_h1_2026)

  Powertrain  H1_2025  H1_2026       YoY_%
0        HEV  2233075  2330877    4.379701
1       MHEV    73672    87465   18.722174
2       PHEV    92931    95428    2.686940
3       FCEV      492      360  -26.829268
4        BEV    82085   193172  135.331668

In [7]:
reported_h1_2025 = pd.to_numeric(electrified_2026.iloc[39, 37])
reported_h1_2026 = pd.to_numeric(electrified_2026.iloc[39, 44])

calculated_h1_2025 = electrified_h1_2026["H1_2025"].sum()
calculated_h1_2026 = electrified_h1_2026["H1_2026"].sum()

print("H1 2025 calculated:", f"{calculated_h1_2025:,.0f}")
print("H1 2025 reported:  ", f"{reported_h1_2025:,.0f}")
print("Difference:        ", f"{calculated_h1_2025 - reported_h1_2025:,.0f}")

print()

print("H1 2026 calculated:", f"{calculated_h1_2026:,.0f}")
print("H1 2026 reported:  ", f"{reported_h1_2026:,.0f}")
print("Difference:        ", f"{calculated_h1_2026 - reported_h1_2026:,.0f}")

H1 2025 calculated: 2,482,255
H1 2025 reported:   2,482,255
Difference:         0

H1 2026 calculated: 2,707,302
H1 2026 reported:   2,707,302
Difference:         0

In [10]:
total_h1_2025 = h1_2026.loc[
    h1_2026["Metric"] == "Worldwide sales", "H1_2025"
].iloc[0]

total_h1_2026 = h1_2026.loc[
    h1_2026["Metric"] == "Worldwide sales", "H1_2026"
].iloc[0]

electrified_total_h1_2025 = reported_h1_2025
electrified_total_h1_2026 = reported_h1_2026

electrification_rate_2025 = (
    electrified_total_h1_2025 / total_h1_2025 * 100
)

electrification_rate_2026 = (
    electrified_total_h1_2026 / total_h1_2026 * 100
)

print(f"H1 2025 electrification rate: {electrification_rate_2025:.2f}%")
print(f"H1 2026 electrification rate: {electrification_rate_2026:.2f}%")
print(
    f"Change: "
    f"{electrification_rate_2026 - electrification_rate_2025:+.2f} percentage points"
)

NameError: name 'h1_2026' is not defined

In [9]:
regional_electrified_h1_2026 = pd.DataFrame({
    "Region": [
        "Japan",
        "North America",
        "Europe",
        "Asia (Excluding China)",
        "China",
        "Other"
    ],
    "H1_2025": [
        electrified_2026.iloc[41, 37],
        electrified_2026.iloc[45, 37],
        electrified_2026.iloc[47, 37],
        electrified_2026.iloc[49, 37],
        electrified_2026.iloc[51, 37],
        electrified_2026.iloc[53, 37]
    ],
    "H1_2026": [
        electrified_2026.iloc[41, 44],
        electrified_2026.iloc[45, 44],
        electrified_2026.iloc[47, 44],
        electrified_2026.iloc[49, 44],
        electrified_2026.iloc[51, 44],
        electrified_2026.iloc[53, 44]
    ]
})

regional_electrified_h1_2026["H1_2025"] = pd.to_numeric(
    regional_electrified_h1_2026["H1_2025"], errors="coerce"
)

regional_electrified_h1_2026["H1_2026"] = pd.to_numeric(
    regional_electrified_h1_2026["H1_2026"], errors="coerce"
)

display(regional_electrified_h1_2026)

                   Region  H1_2025  H1_2026
0                   Japan   480868   499615
1           North America   700971   793726
2                  Europe   475108   533389
3  Asia (Excluding China)   184165   239618
4                   China   438504   439939
5                   Other   202639   201015

In [13]:
sales_region_2026 = pd.read_excel(
    "production_sales_figures_2026-06.xlsx",
    sheet_name="Sales by country or region",
    header=None
)

print(sales_region_2026.shape)

(48, 79)

In [14]:
china_row = sales_region_2026[
    sales_region_2026[3].astype(str).str.contains(
        "China", case=False, na=False
    )
]

display(china_row[[3, 60, 75]])

Empty DataFrame
Columns: [3, 60, 75]
Index: []

In [15]:
display(china_row)

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78]
Index: []

[0 rows x 79 columns]

In [16]:
display(sales_region_2026.iloc[20:24, [3, 60, 75]])

         3        60       75
20   499255   292397   306206
21  2622304  1544011  1436054
22  1302357   837744   694670
23   371272   127706   130512

In [21]:
# Build matched regional sales data

regional_sales_matched = pd.DataFrame({
    "Region": [
        "Japan",
        "North America",
        "Europe",
        "Asia (Excluding China)",
        "China"
    ],
    "H1_2025": [
        768445,
        1438981,
        612007,
        1544011 - 837744,
        837744
    ],
    "H1_2026": [
        804721,
        1452343,
        612271,
        1436054 - 694670,
        694670
    ]
})

display(regional_sales_matched)

                   Region  H1_2025  H1_2026
0                   Japan   768445   804721
1           North America  1438981  1452343
2                  Europe   612007   612271
3  Asia (Excluding China)   706267   741384
4                   China   837744   694670

In [23]:
regional_electrified_matched = pd.DataFrame({
    "Region": [
        "Japan",
        "North America",
        "Europe",
        "Asia (Excluding China)",
        "China"
    ],
    "H1_2025": [
        480868,
        700971,
        475108,
        184165,
        438504
    ],
    "H1_2026": [
        499615,
        793726,
        533389,
        239618,
        439939
    ]
})

# Calculate electrification rates
regional_electrification = regional_sales_matched.copy()

regional_electrification["Electrified_2025"] = regional_electrified_matched["H1_2025"]
regional_electrification["Electrified_2026"] = regional_electrified_matched["H1_2026"]

regional_electrification["Rate_2025_%"] = (
    regional_electrification["Electrified_2025"]
    / regional_electrification["H1_2025"]
    * 100
)

regional_electrification["Rate_2026_%"] = (
    regional_electrification["Electrified_2026"]
    / regional_electrification["H1_2026"]
    * 100
)

regional_electrification["Change_pp"] = (
    regional_electrification["Rate_2026_%"]
    - regional_electrification["Rate_2025_%"]
)

display(regional_electrification.round(2))

,Region,H1_2025,H1_2026,Electrified_2025,Electrified_2026,Rate_2025_%,Rate_2026_%,Change_pp
0,Japan,768445,804721,480868,499615,62.58,62.09,-0.49
1,North America,1438981,1452343,700971,793726,48.71,54.65,5.94
2,Europe,612007,612271,475108,533389,77.63,87.12,9.49
3,Asia (Excluding China),706267,741384,184165,239618,26.08,32.32,6.24
4,China,837744,694670,438504,439939,52.34,63.33,10.99

In [24]:
print("H1 2025 regional total:",
     regional_electrified_matched["H1_2025"].sum())

print("H1 2025 global total: 2,482,255")
print()

print("H1 2025 regional total:",
     regional_electrified_matched["H1_2026"].sum())

print("H1 2026 global total: 2,707,302")

H1 2025 regional total: 2279616
H1 2025 global total: 2,482,255

H1 2025 regional total: 2506287
H1 2026 global total: 2,707,302

In [25]:
electrified_2025_total = (
     480868 + 700971 + 475108 +
    184165 + 438504 + 202639

)
electrified_2026_total = (
    499615 + 793726 + 533389 +
    239618 + 439939 + 201015
)

print("Calculate H1 2025 total:", electrified_2025_total)
print("Official H1 2025 total: 2,482,255")
print()
print("Calculated H1 2026 total:", electrified_2026_total)
print("Official H1 2026 total: 2,707,302")

Calculate H1 2025 total: 2482255
Official H1 2025 total: 2,482,255

Calculated H1 2026 total: 2707302
Official H1 2026 total: 2,707,302

In [26]:
regional_electrification.to_csv(
     "toyota_regional_electrification_h1_2025_2026.csv",
    index = False
)
print("Saved successfuly")

Saved successfuly

In [29]:
import pandas as pd 
toyota_electrified_sales_2016_2025 = pd.read_csv(
    "toyota_electrified_sales_2016_2025.csv"
    
)
display(toyota_electrified_sales_2016_2025)

    Year Powertrain      Sales
0   2016        HEV  1397777.0
1   2017        HEV  1466922.0
2   2018        HEV  1584074.0
3   2019        HEV  1860188.0
4   2020        HEV  1902621.0
5   2021        HEV  2482236.0
6   2022        HEV  2603019.0
7   2023        HEV  3420078.0
8   2024        HEV  4142412.0
9   2025        HEV  4433503.0
10  2016       MHEV        0.0
11  2017       MHEV        0.0
12  2018       MHEV        0.0
13  2019       MHEV     4602.0
14  2020       MHEV     3320.0
15  2021       MHEV     7482.0
16  2022       MHEV     4520.0
17  2023       MHEV    26859.0
18  2024       MHEV    94810.0
19  2025       MHEV   177152.0
20  2016       PHEV     2866.0
21  2017       PHEV    51006.0
22  2018       PHEV    46667.0
23  2019       PHEV    56524.0
24  2020       PHEV    48513.0
25  2021       PHEV   111882.0
26  2022       PHEV    90346.0
27  2023       PHEV   124653.0
28  2024       PHEV   153829.0
29  2025       PHEV   183845.0
30  2016       FCEV     2046.0
31  2017       FCEV     2739.0
32  2018       FCEV     2457.0
33  2019       FCEV     2494.0
34  2020       FCEV     1770.0
35  2021       FCEV     5918.0
36  2022       FCEV     3924.0
37  2023       FCEV     4023.0
38  2024       FCEV     1778.0
39  2025       FCEV     1257.0
40  2016        BEV        4.0
41  2017        BEV        0.0
42  2018        BEV        1.0
43  2019        BEV        0.0
44  2020        BEV     3346.0
45  2021        BEV    14407.0
46  2022        BEV    24466.0
47  2023        BEV   104018.0
48  2024        BEV   139892.0
49  2025        BEV   199137.0
50  2016      Total  1402693.0
51  2017      Total  1520667.0
52  2018      Total  1633199.0
53  2019      Total  1923808.0
54  2020      Total  1959570.0
55  2021      Total  2621925.0
56  2022      Total  2726275.0
57  2023      Total  3679631.0
58  2024      Total  4532721.0
59  2025      Total  4994894.0

In [37]:
total_sales = toyota_electrified_sales_2016_2025[
     toyota_electrified_sales_2016_2025["Powertrain"] == "Total"
][["Year", "Sales"]].rename(columns = {"Sales": "Total_Sales"})

electrified_sales = toyota_electrified_sales_2016_2025[
toyota_electrified_sales_2016_2025["Powertrain"] != "Total"
].groupby("Year", as_index = False)["Sales"].sum()

electrified_sales = electrified_sales.rename(
    columns ={"Sales": "Electrified_Sales"}
)

electrification_trend = total_sales.merge(
    electrified_sales,
    on = "Year"
)

electrification_trend["Electrification_Rate_%"] = (
    electrification_trend["Electrified_Sales"]
    / electrification_trend["Total_Sales"]
    * 100
)

display(electrification_trend.round(2))

   Year  Total_Sales  Electrified_Sales  Electrification_Rate_%
0  2016    1402693.0          1402693.0                   100.0
1  2017    1520667.0          1520667.0                   100.0
2  2018    1633199.0          1633199.0                   100.0
3  2019    1923808.0          1923808.0                   100.0
4  2020    1959570.0          1959570.0                   100.0
5  2021    2621925.0          2621925.0                   100.0
6  2022    2726275.0          2726275.0                   100.0
7  2023    3679631.0          3679631.0                   100.0
8  2024    4532721.0          4532721.0                   100.0
9  2025    4994894.0          4994894.0                   100.0

In [38]:
sales_2025 = pd.read_excel(
    "production_sales_figures_en_202512.xlsx",
    sheet_name="Sales",
    header=None
)

display(sales_2025.iloc[:10, :12])

,0,1,2,3,4,5,6,7,8,9,10,11
0,NaN,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,2.016000e+03,2.017000e+03,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03,2.022000e+03,Jan.2023,Feb.2023
3,NaN,Toyota (incl. Lexus),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Worldwide sales\nCorresponding month: \nFirst ...,9.223727e+06,9.383780e+06,9.541748e+06,9.714253e+06,8.692168e+06,9.615157e+06,9.567184e+06,709870,773271
5,NaN,NaN,NaN,3.827368e-01,1.735231e+00,1.683415e+00,1.807897e+00,-1.052150e+01,1.061863e+01,-4.989310e-01,-5.621847,10.256381
6,NaN,NaN,Sales inside of Japan\nCorresponding month: \n...,1.580851e+06,1.633161e+06,1.564309e+06,1.610169e+06,1.504221e+06,1.476136e+06,1.289132e+06,130218,155840
7,NaN,NaN,NaN,5.540004e+00,3.308977e+00,-4.215873e+00,2.931646e+00,-6.579930e+00,-1.867079e+00,-1.266848e+01,17.982079,53.213914
8,NaN,NaN,Sales outside of Japan\nCorresponding month: F...,7.642876e+06,7.750619e+06,7.977439e+06,8.104084e+06,7.187947e+06,8.139021e+06,8.278052e+06,579652,617431
9,NaN,NaN,NaN,-6.217127e-01,1.409718e+00,2.926476e+00,1.587540e+00,-1.130463e+01,1.323151e+01,1.708203e+00,-9.681139,2.969523

In [39]:
display(sales_2025.iloc[2:5, 4:36])

,4,5,6,7,8,9,10,11,12,13,...,26,27,28,29,30,31,32,33,34,35
2,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,Jan.2023,Feb.2023,Mar.2023,Apr.2023,...,Apr.2024,May.2024,Jun.2024,Jul.2024,Aug.2024,Sep.2024,Oct.2024,Nov.2024,Dec.2024,2024.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9383780.0,9541748.0,9714253.0,8692168.0,9615157.0,9567184.0,709870,773271,916205,800863,...,797088,840680,853082,857969,826862,853149,903103,920569,905426,10159336.0

In [40]:
year_columns = {}

for col in sales_2025.columns:
    value = sales_2025.iloc[2, col]

    if pd.notna(value):
        try:
            year = int(float(value))
            if 2016 <= year <= 2025:
                year_columns[year] = col
        except:
            pass

print(year_columns)

{2016: 3, 2017: 4, 2018: 5, 2019: 6, 2020: 7, 2021: 8, 2022: 9, 2023: 22, 2024: 35}

In [42]:
for col in sales_2025.columns:
    value = sales_2025.iloc[2, col]

    if pd.notna(value) and str(value).startswith("2025"):
        print("Column:", col, "Header:", value)

Column: 49 Header: 2025 Cumulative Total

In [43]:
# Add 2025 column
year_columns[2025] = 49

# Extract Toyota worldwide sales (row 4)
toyota_total_sales = pd.DataFrame({
    "Year": list(year_columns.keys()),
    "Total_Sales": [
        sales_2025.iloc[4, year_columns[year]]
        for year in year_columns
    ]
})

display(toyota_total_sales)

   Year  Total_Sales
0  2016    9223727.0
1  2017    9383780.0
2  2018    9541748.0
3  2019    9714253.0
4  2020    8692168.0
5  2021    9615157.0
6  2022    9567184.0
7  2023   10307395.0
8  2024   10159336.0
9  2025   10536807.0

In [44]:
# Merge total Toyota sales with electrified sales

electrification_trend = toyota_total_sales.merge(
    toyota_electrified_sales_2016_2025[
        toyota_electrified_sales_2016_2025["Powertrain"] == "Total"
    ][["Year", "Sales"]],
    on="Year"
)

electrification_trend = electrification_trend.rename(
    columns={"Sales": "Electrified_Sales"}
)

# Calculate electrification rate
electrification_trend["Electrification_Rate_%"] = (
    electrification_trend["Electrified_Sales"]
    / electrification_trend["Total_Sales"]
    * 100
)

display(electrification_trend.round(2))

   Year  Total_Sales  Electrified_Sales  Electrification_Rate_%
0  2016    9223727.0          1402693.0                   15.21
1  2017    9383780.0          1520667.0                   16.21
2  2018    9541748.0          1633199.0                   17.12
3  2019    9714253.0          1923808.0                   19.80
4  2020    8692168.0          1959570.0                   22.54
5  2021    9615157.0          2621925.0                   27.27
6  2022    9567184.0          2726275.0                   28.50
7  2023   10307395.0          3679631.0                   35.70
8  2024   10159336.0          4532721.0                   44.62
9  2025   10536807.0          4994894.0                   47.40

In [45]:
electrification_trend.to_csv(
    "toyota_electrification_trend_2016_2025.csv",
    index=False
)

print("Saved successfully.")

Saved successfully.

In [50]:
powertrain_2025 = toyota_electrified_sales_2016_2025[
    (toyota_electrified_sales_2016_2025["Year"] == 2025) &
    (toyota_electrified_sales_2016_2025["Powertrain"] != "Total")
].copy()

powertrain_2025["Share_%"] = (
    powertrain_2025["Sales"]
    / powertrain_2025["Sales"].sum()
    * 100
)

display(powertrain_2025.round(2))

    Year Powertrain      Sales  Share_%
9   2025        HEV  4433503.0    88.76
19  2025       MHEV   177152.0     3.55
29  2025       PHEV   183845.0     3.68
39  2025       FCEV     1257.0     0.03
49  2025        BEV   199137.0     3.99

In [52]:
powertrain_trend = toyota_electrified_sales_2016_2025[
    toyota_electrified_sales_2016_2025["Powertrain"] != "Total"
].copy()

display(powertrain_trend)

    Year Powertrain      Sales
0   2016        HEV  1397777.0
1   2017        HEV  1466922.0
2   2018        HEV  1584074.0
3   2019        HEV  1860188.0
4   2020        HEV  1902621.0
5   2021        HEV  2482236.0
6   2022        HEV  2603019.0
7   2023        HEV  3420078.0
8   2024        HEV  4142412.0
9   2025        HEV  4433503.0
10  2016       MHEV        0.0
11  2017       MHEV        0.0
12  2018       MHEV        0.0
13  2019       MHEV     4602.0
14  2020       MHEV     3320.0
15  2021       MHEV     7482.0
16  2022       MHEV     4520.0
17  2023       MHEV    26859.0
18  2024       MHEV    94810.0
19  2025       MHEV   177152.0
20  2016       PHEV     2866.0
21  2017       PHEV    51006.0
22  2018       PHEV    46667.0
23  2019       PHEV    56524.0
24  2020       PHEV    48513.0
25  2021       PHEV   111882.0
26  2022       PHEV    90346.0
27  2023       PHEV   124653.0
28  2024       PHEV   153829.0
29  2025       PHEV   183845.0
30  2016       FCEV     2046.0
31  2017       FCEV     2739.0
32  2018       FCEV     2457.0
33  2019       FCEV     2494.0
34  2020       FCEV     1770.0
35  2021       FCEV     5918.0
36  2022       FCEV     3924.0
37  2023       FCEV     4023.0
38  2024       FCEV     1778.0
39  2025       FCEV     1257.0
40  2016        BEV        4.0
41  2017        BEV        0.0
42  2018        BEV        1.0
43  2019        BEV        0.0
44  2020        BEV     3346.0
45  2021        BEV    14407.0
46  2022        BEV    24466.0
47  2023        BEV   104018.0
48  2024        BEV   139892.0
49  2025        BEV   199137.0

In [53]:
powertrain_trend_wide = powertrain_trend.pivot(
    index = "Year",
    columns = "Powertrain",
    values = "Sales"
    
).reset_index()
display(powertrain_trend_wide)

Powertrain  Year       BEV    FCEV        HEV      MHEV      PHEV
0           2016       4.0  2046.0  1397777.0       0.0    2866.0
1           2017       0.0  2739.0  1466922.0       0.0   51006.0
2           2018       1.0  2457.0  1584074.0       0.0   46667.0
3           2019       0.0  2494.0  1860188.0    4602.0   56524.0
4           2020    3346.0  1770.0  1902621.0    3320.0   48513.0
5           2021   14407.0  5918.0  2482236.0    7482.0  111882.0
6           2022   24466.0  3924.0  2603019.0    4520.0   90346.0
7           2023  104018.0  4023.0  3420078.0   26859.0  124653.0
8           2024  139892.0  1778.0  4142412.0   94810.0  153829.0
9           2025  199137.0  1257.0  4433503.0  177152.0  183845.0

In [55]:
powertrain_growth = pd.DataFrame({
    "Powertrain":["HEV", "MHEV", "PHEV", "FCEV", "BEV"],


"Powertrain": ["HEV", "MHEV", "PHEV", "FCEV", "BEV"],
    "2016_Sales": [
        powertrain_trend_wide.loc[powertrain_trend_wide["Year"] == 2016, "HEV"].iloc[0],
        powertrain_trend_wide.loc[powertrain_trend_wide["Year"] == 2016, "MHEV"].iloc[0],
        powertrain_trend_wide.loc[powertrain_trend_wide["Year"] == 2016, "PHEV"].iloc[0],
        powertrain_trend_wide.loc[powertrain_trend_wide["Year"] == 2016, "FCEV"].iloc[0],
        powertrain_trend_wide.loc[powertrain_trend_wide["Year"] == 2016, "BEV"].iloc[0]
    ],
    "2025_Sales": [
        powertrain_trend_wide.loc[powertrain_trend_wide["Year"] == 2025, "HEV"].iloc[0],
        powertrain_trend_wide.loc[powertrain_trend_wide["Year"] == 2025, "MHEV"].iloc[0],
        powertrain_trend_wide.loc[powertrain_trend_wide["Year"] == 2025, "PHEV"].iloc[0],
        powertrain_trend_wide.loc[powertrain_trend_wide["Year"] == 2025, "FCEV"].iloc[0],
        powertrain_trend_wide.loc[powertrain_trend_wide["Year"] == 2025, "BEV"].iloc[0]
    ]
})
powertrain_growth["Absolute_Change"] = (
    powertrain_growth["2025_Sales"]
    - powertrain_growth["2016_Sales"]
)

display(powertrain_growth)

  Powertrain  2016_Sales  2025_Sales  Absolute_Change
0        HEV   1397777.0   4433503.0        3035726.0
1       MHEV         0.0    177152.0         177152.0
2       PHEV      2866.0    183845.0         180979.0
3       FCEV      2046.0      1257.0           -789.0
4        BEV         4.0    199137.0         199133.0