In [1]:
import pandas as pd 
toyota_clean = pd.read_excel("toyota_clean.xlsx")
regional_sales = pd.read_csv("toyota_regional_sales_2016_2025.csv")
electrified_sales = pd.read_csv("toyota_electrified_sales_2016_2025.csv") 
regional_electrified = pd.read_csv("toyota_regional_electrified_sales_2016_2025.csv")

print("Toyota specs:", toyota_clean.shape)
print("Regional sales :",regional_sales.shape)
print("Electrified sales:", electrified_sales.shape)
print("Region electrified:", regional_electrified.shape)

Toyota specs: (385, 21)
Regional sales : (90, 3)
Electrified sales: (60, 3)
Region electrified: (50, 3)

In [2]:
sales_2016_2025 = pd.DataFrame({
    "Year": range(2016, 2026),
    "Sales": [
        9223727,
        9383780,
        9541748,
        9714253,
        8692168,
        9615157,
        9567184,
        10307395,
        10159336,
        10536807
    ]
})

sales_2016_2025["YoY_%"] = (
    sales_2016_2025["Sales"].pct_change() * 100
)

display(sales_2016_2025.round(2))

   Year     Sales  YoY_%
0  2016   9223727    NaN
1  2017   9383780   1.74
2  2018   9541748   1.68
3  2019   9714253   1.81
4  2020   8692168 -10.52
5  2021   9615157  10.62
6  2022   9567184  -0.50
7  2023  10307395   7.74
8  2024  10159336  -1.44
9  2025  10536807   3.72

In [3]:
regional_2025 = regional_sales[
    regional_sales["Year"] == 2025
].copy()

regional_2025 = regional_2025.sort_values(
    "Sales",
    ascending = False
)
display(regional_2025)

    Year         Region      Sales
39  2025           Asia  3285605.0
9   2025  North America  2929660.0
49  2025          Japan  1501263.0
29  2025         Europe  1182551.0
69  2025    Middle East   600891.0
19  2025  Latin America   472049.0
59  2025        Oceania   300560.0
79  2025         Africa   264228.0
89  2025         Others        NaN

In [4]:
region_pivot = regional_sales.pivot(
    index = "Region",
    columns = "Year",
    values = "Sales"
)

region_growth = pd.DataFrame({
    "Sales_2016": region_pivot[2016],
    "Sales_2025": region_pivot[2025],
    
})

region_growth["Change"] = (
    region_growth["Sales_2025"] - region_growth["Sales_2016"]
    
)
region_growth["Growth_%"]= (
    region_growth["Change"] /
    region_growth["Sales_2016"] * 100
)

region_growth = region_growth.sort_values(
    "Growth_%",
    ascending = False
)

display(region_growth.round(2))

               Sales_2016  Sales_2025    Change  Growth_%
Region
Africa           180994.0    264228.0   83234.0     45.99
Europe           898019.0   1182551.0  284532.0     31.68
Asia            2531974.0   3285605.0  753631.0     29.76
Latin America    391794.0    472049.0   80255.0     20.48
Oceania          256395.0    300560.0   44165.0     17.23
North America   2797542.0   2929660.0  132118.0      4.72
Middle East      584389.0    600891.0   16502.0      2.82
Japan           1580851.0   1501263.0  -79588.0     -5.03
Others             1769.0         NaN       NaN       NaN

In [5]:
region_contribution = region_growth[
["Sales_2016","Sales_2025", "Change"]
].sort_values(
    "Change",
    ascending = False
)

display(region_contribution.round(0))

               Sales_2016  Sales_2025    Change
Region
Asia            2531974.0   3285605.0  753631.0
Europe           898019.0   1182551.0  284532.0
North America   2797542.0   2929660.0  132118.0
Africa           180994.0    264228.0   83234.0
Latin America    391794.0    472049.0   80255.0
Oceania          256395.0    300560.0   44165.0
Middle East      584389.0    600891.0   16502.0
Japan           1580851.0   1501263.0  -79588.0
Others             1769.0         NaN       NaN

In [6]:
region_contribution = region_contribution.copy()

region_contribution["Sales_2016"] = (
    region_contribution["Sales_2016"].round().astype("Int64")
)

region_contribution["Sales_2025"]  = (
    region_contribution["Sales_2025"].round().astype("Int64")
)

region_contribution["Change"] = (
    region_contribution["Change"].round().astype("Int64")
)

display(region_contribution)

               Sales_2016  Sales_2025  Change
Region
Asia              2531974     3285605  753631
Europe             898019     1182551  284532
North America     2797542     2929660  132118
Africa             180994      264228   83234
Latin America      391794      472049   80255
Oceania            256395      300560   44165
Middle East        584389      600891   16502
Japan             1580851     1501263  -79588
Others               1769        <NA>    <NA>

In [7]:
regional_electrified_2025 = regional_electrified[
    regional_electrified["Year"] == 2025
].copy()

regional_electrified_2025 = regional_electrified_2025.sort_values(
    "Electrified_Sales",
    ascending=False
)

display(regional_electrified_2025)

    Year                  Region  Electrified_Sales
9   2025           North America          1363916.0
39  2025                   China           958733.0
19  2025                  Europe           913797.0
29  2025  Asia (Excluding China)           423138.0
49  2025                   Other           422943.0

In [8]:
sales_2025 = regional_sales[
    sales_2025["Year"] == 2025
].copy()

sales_2025 = sales_2025[
    sales_2025["Region"].isin(
        ["North America", "Europe", "Asia"]
    )
].copy()

sales_2025["Electrified_Region"] = sales_2025["Region"]

sales_2025.loc[
    sales_2025["Region"] == "Asia",
    "Electrified_Region"
] = "Asia (Excluding China)"

electrified_2025  = regional_electrified[
    regional_electrified["Year"] == 2025
].copy()

electrified_2025 = electrified_2025[
    electrified_2025["Region"].isin(
        ["North America", "Europe", "Asia (Excluding China", "China"]
    )
].copy()

china_sales = pd.DataFrame({
    "Electrified_Region": ["China"],
    "Total_Sales": [None]
})

sales_2025 = sales_2025[
    ["Electrified_Region", "Sales"]
].rename(
    columns = {"Sales": "Total_Sales"}
)

china = regional_sales[
    (regional_sales["Year"] == 2025) &
    (regional_sales["Region"] == "Asia")
]

comparison = sales_2025.merge(
    electrified_2025[
        ["Region", "Electrified_Sales"]
    ],
    left_on = "Electrified_Region",
    right_on = "Region",
    how = "inner"
)

comparison = comparison[
    ["ELectrified_Region", "Total_Sales", "Electrified_Sales"]
]
comparison["Electrified_Rate_%"] = (
    comparison["Electrified_Sales"] /
    comparison["Total_Sales"] * 100
)

display(comparison.round(2))

NameError: name 'sales_2025' is not defined

In [9]:
# 2025 total sales
sales_2025 = regional_sales[
    regional_sales["Year"] == 2025
].copy()

sales_2025 = sales_2025[
    sales_2025["Region"].isin(
        ["North America", "Europe", "Asia"]
    )
].copy()

# Rename Asia so it matches the electrified dataset
sales_2025["Electrified_Region"] = sales_2025["Region"]

sales_2025.loc[
    sales_2025["Region"] == "Asia",
    "Electrified_Region"
] = "Asia (Excluding China)"

# 2025 electrified sales
electrified_2025 = regional_electrified[
    regional_electrified["Year"] == 2025
].copy()

electrified_2025 = electrified_2025[
    electrified_2025["Region"].isin(
        ["North America", "Europe", "Asia (Excluding China)", "China"]
    )
].copy()

# Add China total sales separately
china_sales = pd.DataFrame({
    "Electrified_Region": ["China"],
    "Total_Sales": [None]
})

# Prepare matched sales
sales_2025 = sales_2025[
    ["Electrified_Region", "Sales"]
].rename(
    columns={"Sales": "Total_Sales"}
)

# Add China sales from the regional sales dataframe
china = regional_sales[
    (regional_sales["Year"] == 2025) &
    (regional_sales["Region"] == "Asia")
]

# We cannot separate China from the 2025 sales dataset here,
# so leave China out of this calculation for now.

comparison = sales_2025.merge(
    electrified_2025[
        ["Region", "Electrified_Sales"]
    ],
    left_on="Electrified_Region",
    right_on="Region",
    how="inner"
)

comparison = comparison[
    ["Electrified_Region", "Total_Sales", "Electrified_Sales"]
]

comparison["Electrification_Rate_%"] = (
    comparison["Electrified_Sales"] /
    comparison["Total_Sales"] * 100
)

display(comparison.round(2))

,Electrified_Region,Total_Sales,Electrified_Sales,Electrification_Rate_%
0,North America,2929660.0,1363916.0,46.56
1,Europe,1182551.0,913797.0,77.27
2,Asia (Excluding China),3285605.0,423138.0,12.88

In [10]:
display(
    regional_sales[
    (regional_sales["Year"] == 2025) &
    (regional_sales["Region"] == "Asia")
    ]
)

    Year Region      Sales
39  2025   Asia  3285605.0

In [11]:
print(electrified_2025["Region"].tolist())

['North America', 'Europe', 'Asia (Excluding China)', 'China']

In [12]:
# 2025 total sales
sales_2025 = regional_sales[
    (regional_sales["Year"] == 2025) &
    (regional_sales["Region"].isin(
        ["North America", "Europe", "Asia"]
    ))
].copy()

# 2025 electrified sales
electrified_2025 = regional_electrified[
    regional_electrified["Year"] == 2025
].copy()

# Get electrified sales
north_america = electrified_2025.loc[
    electrified_2025["Region"] == "North America",
    "Electrified_Sales"
].iloc[0]

europe = electrified_2025.loc[
    electrified_2025["Region"] == "Europe",
    "Electrified_Sales"
].iloc[0]

asia_ex_china = electrified_2025.loc[
    electrified_2025["Region"] == "Asia (Excluding China)",
    "Electrified_Sales"
].iloc[0]

china = electrified_2025.loc[
    electrified_2025["Region"] == "China",
    "Electrified_Sales"
].iloc[0]

# Combine China + Asia excluding China
asia_electrified = asia_ex_china + china

# Get total sales
na_sales = sales_2025.loc[
    sales_2025["Region"] == "North America",
    "Sales"
].iloc[0]

europe_sales = sales_2025.loc[
    sales_2025["Region"] == "Europe",
    "Sales"
].iloc[0]

asia_sales = sales_2025.loc[
    sales_2025["Region"] == "Asia",
    "Sales"
].iloc[0]

# Build comparison table
comparison = pd.DataFrame({
    "Region": [
        "North America",
        "Europe",
        "Asia"
    ],
    "Total_Sales": [
        na_sales,
        europe_sales,
        asia_sales
    ],
    "Electrified_Sales": [
        north_america,
        europe,
        asia_electrified
    ]
})

comparison["Electrification_Rate_%"] = (
    comparison["Electrified_Sales"] /
    comparison["Total_Sales"] * 100
)

display(comparison.round(2))

          Region  Total_Sales  Electrified_Sales  Electrification_Rate_%
0  North America    2929660.0          1363916.0                   46.56
1         Europe    1182551.0           913797.0                   77.27
2           Asia    3285605.0          1381871.0                   42.06

In [13]:
electrified_2025_global = electrified_sales[
    electrified_sales["Year"] == 2025
].copy()

display (electrified_2025_global)

    Year Powertrain      Sales
9   2025        HEV  4433503.0
19  2025       MHEV   177152.0
29  2025       PHEV   183845.0
39  2025       FCEV     1257.0
49  2025        BEV   199137.0
59  2025      Total  4994894.0

In [14]:
global_sales_2025 = 10_536_807

global_electrified_2025 = electrified_2025_global.loc[
electrified_2025_global["Powertrain"] == "Total", "Sales"
].iloc[0]

global_electrification_rate = (
    global_electrified_2025 / global_sales_2025 * 100
)

print(f"2025 Global Sales:{global_sales_2025:,}")
print(f"2025 Global ELectrified Sales:{global_electrified_2025:,.0f}")
print(f"2025 Global Electrification Rate: {global_electrification_rate:,.2f}%")

2025 Global Sales:10,536,807
2025 Global ELectrified Sales:4,994,894
2025 Global Electrification Rate: 47.40%

In [15]:
electrification_trend = sales_2016_2025.merge(
    electrified_sales[
        electrified_sales["Powertrain"] == "Total"
    ][["Year","Sales"]].rename(
        columns = {"Sales" : "Electrified_Sales"}
    ),
    on = "Year",
    how = "inner"
)
electrification_trend ["Electrification_Rate_%"] = (
    electrification_trend["Electrified_Sales"] /
    electrification_trend["Sales"] * 100
)

display(
    electrification_trend[
        ["Year", "Sales", "Electrified_Sales", "Electrification_Rate_%"]
    ].round(2)
)

   Year     Sales  Electrified_Sales  Electrification_Rate_%
0  2016   9223727          1402693.0                   15.21
1  2017   9383780          1520667.0                   16.21
2  2018   9541748          1633199.0                   17.12
3  2019   9714253          1923808.0                   19.80
4  2020   8692168          1959570.0                   22.54
5  2021   9615157          2621925.0                   27.27
6  2022   9567184          2726275.0                   28.50
7  2023  10307395          3679631.0                   35.70
8  2024  10159336          4532721.0                   44.62
9  2025  10536807          4994894.0                   47.40

In [16]:
powertrain_trend = electrified_sales[
    electrified_sales["Powertrain"] != "Total"
].pivot(
    index = "Year",
    columns = "Powertrain",
    values = "Sales"
)
powertrain_change = pd.DataFrame({
    "Sales_2016" : powertrain_trend.loc[2016],
    "Sales_2025" : powertrain_trend.loc[2025]
}) 

powertrain_change["Change"] = (
    powertrain_change["Sales_2025"],
    powertrain_change["Sales_2016"]
)

powertrain["Growth_%"] = (
    powertrain_change["Change"] /
    powertrain_change["Sales_2016"] * 100
) 

display(Powertrain_change.round(2))

ValueError: Length of values (2) does not match length of index (5)

In [17]:
powertrain_trend = electrified_sales[
    electrified_sales["Powertrain"] != "Total"
].pivot(
    index="Year",
    columns="Powertrain",
    values="Sales"
)

powertrain_change = pd.DataFrame({
    "Sales_2016": powertrain_trend.loc[2016],
    "Sales_2025": powertrain_trend.loc[2025]
})

powertrain_change["Change"] = (
    powertrain_change["Sales_2025"] -
    powertrain_change["Sales_2016"]
)

powertrain_change["Growth_%"] = (
    powertrain_change["Change"] /
    powertrain_change["Sales_2016"] * 100
)

display(powertrain_change.round(2))

            Sales_2016  Sales_2025     Change    Growth_%
Powertrain
BEV                4.0    199137.0   199133.0  4978325.00
FCEV            2046.0      1257.0     -789.0      -38.56
HEV          1397777.0   4433503.0  3035726.0      217.18
MHEV               0.0    177152.0   177152.0         inf
PHEV            2866.0    183845.0   180979.0     6314.69

In [18]:
powertrain_mix_2025 = electrified_2025_global[
    electrified_2025_global["Powertrain"] != "Total"
].copy()

total_electrified = electrified_2025_global.loc[
electrified_2025_global["Powertrain"] == "Total",
"Sales"
].iloc[0]

powertrain_mix_2025["Share_of_Electrified_%"] = (
    powertrain_mix_2025["Sales"] / 
    total_electrified * 100
)

display(
    powertrain_mix_2025[
    ["Powertrain", "Sales", "Share_of_Electrified_%"]
    ].sort_values(
        "Sales",
        ascending =  False
    ).round(2)
)

   Powertrain      Sales  Share_of_Electrified_%
9         HEV  4433503.0                   88.76
49        BEV   199137.0                    3.99
29       PHEV   183845.0                    3.68
19       MHEV   177152.0                    3.55
39       FCEV     1257.0                    0.03

In [19]:
print("Toyota specs:", toyota_clean.shape)
print("Regional sales:", regional_sales.shape)
print("Electrified sales:", electrified_sales.shape)
print("Regional electrified:", regional_electrified.shape)

print("\nToyota spec columns:")
print(toyota_clean.columns.tolist())

Toyota specs: (385, 21)
Regional sales: (90, 3)
Electrified sales: (60, 3)
Regional electrified: (50, 3)

Toyota spec columns:
['make_group', 'make', 'model', 'generation', 'gen_year_start', 'gen_year_end', 'engine_label', 'fuel_type', 'cylinders', 'displacement_cc', 'power_hp', 'torque_nm', 'transmission', 'drivetrain', 'fuel_economy_combined_l100', 'length_mm', 'width_mm', 'height_mm', 'wheelbase_mm', 'curb_weight_kg', 'powertrain_category']

In [20]:
# Major Toyota models from the Integrated Report
major_models = [
    "Corolla",
    "RAV4",
    "Yaris",
    "Camry",
    "Hilux",
    "Highlander",
    "Sienna",
    "Tacoma",
    "Lexus RX",
    "Innova"
]

# Map report names to names used in the cleaned specs dataset
model_mapping = {
    "Highlander": "Highlander / Kluger",
    "RAV4": "RAV4",
}

major_models_specs = []

for report_model in major_models:
    spec_model = model_mapping.get(report_model, report_model)

    subset = toyota_clean[
        toyota_clean["model"] == spec_model
    ]

    major_models_specs.append(
        subset[["model", "powertrain_category"]]
        .drop_duplicates()
        .assign(Report_Model=report_model)
    )

major_models_specs = pd.concat(
    major_models_specs,
    ignore_index=True
)

display(
    major_models_specs[
        ["Report_Model", "model", "powertrain_category"]
    ].sort_values(
        ["Report_Model", "powertrain_category"]
    )
)

   Report_Model                model powertrain_category
7         Camry                Camry                 HEV
8         Camry                Camry                 ICE
0       Corolla              Corolla                 HEV
1       Corolla              Corolla                 ICE
11   Highlander  Highlander / Kluger                 BEV
13   Highlander  Highlander / Kluger                 HEV
12   Highlander  Highlander / Kluger                 ICE
10        Hilux                Hilux                 HEV
9         Hilux                Hilux                 ICE
2          RAV4                 RAV4                 HEV
4          RAV4                 RAV4                 ICE
3          RAV4                 RAV4                PHEV
14       Sienna               Sienna                 HEV
15       Sienna               Sienna                 ICE
16       Tacoma               Tacoma                 HEV
17       Tacoma               Tacoma                 ICE
5         Yaris                Yaris                 HEV
6         Yaris                Yaris                 ICE

In [21]:
model_powertrain_summary = (
    major_models_specs
    .groupby("Report_Model")["powertrain_category"]
    .apply(lambda x: ",".join(sorted(x.unique())))
    .reset_index()
)

display(model_powertrain_summary)

  Report_Model powertrain_category
0        Camry             HEV,ICE
1      Corolla             HEV,ICE
2   Highlander         BEV,HEV,ICE
3        Hilux             HEV,ICE
4         RAV4        HEV,ICE,PHEV
5       Sienna             HEV,ICE
6       Tacoma             HEV,ICE
7        Yaris             HEV,ICE

In [22]:
major_model_names = model_powertrain_summary["Report_Model"].tolist()

major_model_specs = toyota_clean[
    toyota_clean["model"].isin(
        [
            "Camry",
            "Corolla",
            "Highlander / Kluger",
            "Hilux",
            "RAV4",
            "Sienna",
            "Tacoma",
            "Yaris"
        ]
    )
].copy()

major_model_specs = major_model_specs[
    major_model_specs["powertrain_category"].isin(
        ["ICE", "HEV"]
    )
].copy()

display(
    major_model_specs[
        [
            "model",
            "generation",
            "powertrain_category",
            "power_hp",
            "torque_nm",
            "displacement_cc",
            "fuel_economy_combined_l100"
        ]
    ].sort_values(
        ["model", "powertrain_category"]
    )
)

,model,generation,powertrain_category,power_hp,torque_nm,displacement_cc,fuel_economy_combined_l100
71,Camry,Camry (2023),HEV,232.0,NaN,NaN,NaN
72,Camry,Camry (2023),HEV,225.0,NaN,NaN,NaN
73,Camry,Camry (2021),HEV,176.0,221.0,2487.0,4.5
77,Camry,Camry (2020),HEV,218.0,NaN,NaN,NaN
82,Camry,Camry (2017),HEV,178.0,221.0,2487.0,4.3
...,...,...,...,...,...,...,...
374,Yaris,Yaris Hatchback (2013),ICE,86.0,108.0,1197.0,5.0
375,Yaris,Yaris Sedan (2018),ICE,106.0,140.0,1496.0,6.9
376,Yaris,Yaris Sedan (2018),ICE,106.0,140.0,1496.0,6.7
377,Yaris,Yaris Sedan (2016),ICE,107.5,140.0,1496.0,6.7
378,Yaris,Yaris Sedan (2016),ICE,107.5,140.0,1496.0,6.9

In [23]:
missing_by_model = (
    major_model_specs
    .groupby(["model", "powertrain_category"])[
        [
            "power_hp",
            "torque_nm",
            "displacement_cc",
            "fuel_economy_combined_l100"
        ]
    ]
    .apply(lambda x: x.isna().sum())
)

display(missing_by_model)

                                         power_hp  torque_nm  displacement_cc  \
model               powertrain_category
Camry               HEV                         0          4                3
                    ICE                         0          0                0
Corolla             HEV                         0          2                2
                    ICE                         0          0                0
Highlander / Kluger HEV                         0          0                0
                    ICE                         0          0                0
Hilux               HEV                         0          0                0
                    ICE                         0          0                1
RAV4                HEV                         0          0                0
                    ICE                         0          0                0
Sienna              HEV                         0          0                0
                    ICE                         0          0                0
Tacoma              HEV                         0          1                1
                    ICE                         0          0                0
Yaris               HEV                         0          0                0
                    ICE                         0          0                0

                                         fuel_economy_combined_l100
model               powertrain_category
Camry               HEV                                           3
                    ICE                                           1
Corolla             HEV                                           3
                    ICE                                           5
Highlander / Kluger HEV                                           1
                    ICE                                           1
Hilux               HEV                                           0
                    ICE                                           4
RAV4                HEV                                           2
                    ICE                                           0
Sienna              HEV                                           0
                    ICE                                           0
Tacoma              HEV                                           1
                    ICE                                           8
Yaris               HEV                                           1
                    ICE                                           0

In [24]:
missing_specs = major_model_specs[
    major_model_specs[
        [
            "torque_nm",
            "displacement_cc",
            "fuel_economy_combined_l100"
        ]
    ].isna().any(axis=1)
].copy()

display(
    missing_specs[
        [
            "model",
            "generation",
            "powertrain_category",
            "engine_label",
            "power_hp",
            "torque_nm",
            "displacement_cc",
            "fuel_economy_combined_l100"
        ]
    ]
)

,model,generation,powertrain_category,engine_label,power_hp,torque_nm,displacement_cc,fuel_economy_combined_l100
71,Camry,Camry (2023),HEV,2.5L CVT AWD (232 HP),232.0,NaN,NaN,NaN
72,Camry,Camry (2023),HEV,2.5L CVT FWD (225 HP),225.0,NaN,NaN,NaN
77,Camry,Camry (2020),HEV,2.5L 8AT FWD (218 HP),218.0,NaN,NaN,NaN
79,Camry,Camry (2017),ICE,2.0L 6AT FWD (150 HP),150.0,192.0,1998.0,NaN
85,Camry,Camry (2014),HEV,2.5L ECVT FWD (200 HP),203.0,NaN,2494.0,5.7
88,Corolla,Corolla Sedan (2022),HEV,1.8L CVT FWD (140 HP),140.0,NaN,NaN,NaN
89,Corolla,Corolla Sedan (2022),HEV,2.0L CVT FWD (196 HP),196.0,NaN,NaN,NaN
109,Corolla,Corolla Touring (2018),ICE,1.2L VVT-i 6MT FWD (114 HP),114.0,185.0,1197.0,NaN
110,Corolla,Corolla Touring (2018),ICE,1.2L VVT-i CVT FWD (114 HP),114.0,185.0,1197.0,NaN
111,Corolla,Corolla Touring (2018),HEV,1.8L VVT-i FWD (122 HP),122.0,142.0,1798.0,NaN
115,Corolla,Corolla (2014),ICE,1.6L CVT FWD (122 HP),122.0,155.0,1598.0,NaN
116,Corolla,Corolla (2014),ICE,1.8L CVT FWD (139 HP),139.0,174.0,1798.0,NaN
117,Corolla,Corolla (2014),ICE,2.0L CVT FWD (145 HP),145.0,187.0,1987.0,NaN
204,Highlander / Kluger,Highlander / Kluger (2016),HEV,3.5L CVT (306 HP),299.0,357.0,3456.0,NaN
206,Highlander / Kluger,Highlander / Kluger (2013),ICE,3.5L V6 DOHC 6AT AWD (270 HP),273.0,248.0,3456.0,NaN
209,Hilux,Hilux Double Cab (2025),ICE,2.8L Turbo 6AT AWD (204 HP),204.0,500.0,NaN,NaN
215,Hilux,Hilux Double Cab (2017),ICE,2.7L 5MT RWD (166 HP),166.0,245.0,2698.0,NaN
216,Hilux,Hilux Double Cab (2017),ICE,2.7L 6AT RWD (166 HP),166.0,245.0,2698.0,NaN
217,Hilux,Hilux Double Cab (2017),ICE,2.4L 5MT RWD (150 HP),150.0,400.0,2393.0,NaN
267,RAV4,RAV4 5 Doors (2025),HEV,2.5L ECVT AWD (236 HP),183.0,221.0,2487.0,NaN
268,RAV4,RAV4 5 Doors (2025),HEV,2.5L ECVT FWD (226 HP),183.0,221.0,2487.0,NaN
304,Tacoma,Tacoma (2023),HEV,2.4L i-FORCE MAX 8AT AWD (330 HP),330.0,NaN,NaN,NaN
307,Tacoma,Tacoma (2019),ICE,3.5L V6 6AT RWD (278 HP),278.0,359.0,3456.0,NaN
308,Tacoma,Tacoma (2019),ICE,3.5L V6 6MT FWD (278 HP),278.0,359.0,3456.0,NaN
309,Tacoma,Tacoma (2015),ICE,2.7L 5MT AWD (161 HP),161.0,244.0,2693.0,NaN
310,Tacoma,Tacoma (2015),ICE,2.7L 6AT AWD (161 HP),161.0,244.0,2693.0,NaN
311,Tacoma,Tacoma (2015),ICE,2.7L 6AT RWD (161 HP),161.0,244.0,2693.0,NaN
312,Tacoma,Tacoma (2015),ICE,3.5L V6 6AT AWD (282 HP),282.0,359.0,3456.0,NaN
313,Tacoma,Tacoma (2015),ICE,3.5L V6 6AT RWD (282 HP),282.0,359.0,3456.0,NaN
314,Tacoma,Tacoma (2015),ICE,3.5L V6 6MT AWD (282 HP),282.0,359.0,3456.0,NaN
357,Yaris,Yaris 5 Doors (2019),HEV,1.5L eCVT FWD (116 HP),91.0,120.0,1490.0,NaN

In [25]:
# Verified missing-value updates
verified_updates = {
    # Camry 2023 HEV
    71: {
        "torque_nm": 221,
        "displacement_cc": 2487,
        "fuel_economy_combined_l100": 4.8
    },
    72: {
        "torque_nm": 221,
        "displacement_cc": 2487,
        "fuel_economy_combined_l100": 4.6
    },

    # Camry 2020 HEV
    77: {
        "torque_nm": 221,
        "displacement_cc": 2487,
        "fuel_economy_combined_l100": 4.5
    },

    # Corolla 2022 HEV
    88: {
        "torque_nm": 142,
        "displacement_cc": 1798,
        "fuel_economy_combined_l100": 3.8
    },
    89: {
        "torque_nm": 202,
        "displacement_cc": 1987,
        "fuel_economy_combined_l100": 4.5
    },

    # RAV4 2025 HEV
    267: {
        "fuel_economy_combined_l100": 6.0
    },
    268: {
        "fuel_economy_combined_l100": 5.8
    },

    # Tacoma 2023 HEV
    304: {
        "torque_nm": 630,
        "displacement_cc": 2393,
        "fuel_economy_combined_l100": 9.8
    },

    # Yaris 2019 HEV
    357: {
        "fuel_economy_combined_l100": 3.8
    }
}

for row_index, values in verified_updates.items():
    for column, value in values.items():
        if pd.isna(toyota_clean.loc[row_index, column]):
            toyota_clean.loc[row_index, column] = value

In [26]:
display(
    toyota_clean.loc[
        list(verified_updates.keys()),
        [
            "model",
            "generation",
            "powertrain_category",
            "engine_label",
            "power_hp",
            "torque_nm",
            "displacement_cc",
            "fuel_economy_combined_l100"
        ]
    ]
)

,model,generation,powertrain_category,engine_label,power_hp,torque_nm,displacement_cc,fuel_economy_combined_l100
71,Camry,Camry (2023),HEV,2.5L CVT AWD (232 HP),232.0,221.0,2487.0,4.8
72,Camry,Camry (2023),HEV,2.5L CVT FWD (225 HP),225.0,221.0,2487.0,4.6
77,Camry,Camry (2020),HEV,2.5L 8AT FWD (218 HP),218.0,221.0,2487.0,4.5
88,Corolla,Corolla Sedan (2022),HEV,1.8L CVT FWD (140 HP),140.0,142.0,1798.0,3.8
89,Corolla,Corolla Sedan (2022),HEV,2.0L CVT FWD (196 HP),196.0,202.0,1987.0,4.5
267,RAV4,RAV4 5 Doors (2025),HEV,2.5L ECVT AWD (236 HP),183.0,221.0,2487.0,6.0
268,RAV4,RAV4 5 Doors (2025),HEV,2.5L ECVT FWD (226 HP),183.0,221.0,2487.0,5.8
304,Tacoma,Tacoma (2023),HEV,2.4L i-FORCE MAX 8AT AWD (330 HP),330.0,630.0,2393.0,9.8
357,Yaris,Yaris 5 Doors (2019),HEV,1.5L eCVT FWD (116 HP),91.0,120.0,1490.0,3.8

In [27]:
model_comparison = (
    major_model_specs
    .groupby(["model", "powertrain_category"])[
        ["power_hp", "fuel_economy_combined_l100"]
    ]
    .mean()
    .reset_index()
)

display(
    model_comparison.round(2)
)

,model,powertrain_category,power_hp,fuel_economy_combined_l100
0,Camry,HEV,205.33,4.83
1,Camry,ICE,235.33,8.45
2,Corolla,HEV,145.10,4.06
3,Corolla,ICE,128.59,6.25
4,Highlander / Kluger,HEV,236.00,7.13
5,Highlander / Kluger,ICE,263.75,10.19
6,Hilux,HEV,204.00,8.90
7,Hilux,ICE,169.60,8.24
8,RAV4,HEV,176.00,9.42
9,RAV4,ICE,168.71,7.29
10,Sienna,HEV,190.73,6.57
11,Sienna,ICE,284.85,11.22
12,Tacoma,HEV,330.00,NaN
13,Tacoma,ICE,220.30,19.50
14,Yaris,HEV,103.00,3.57
15,Yaris,ICE,102.41,6.03

In [28]:
major_model_sales = pd.DataFrame({
    "Model": [
        "Corolla",
        "RAV4",
        "Yaris",
        "Camry",
        "Hilux",
        "Highlander",
        "Sienna",
        "Tacoma",
        "Lexus RX",
        "Innova"
    ],
    "Sales_Thousands": [
        1661,
        1047,
        908,
        591,
        580,
        323,
        278,
        257,
        224,
        210
    ]
})

major_model_sales = major_model_sales.merge(
    model_powertrain_summary.rename(
        columns={"Report_Model":"Model"}
    ),
    on = "Model",
    how = "left"
)

display(
    major_model_sales.sort_values(
        "Sales_Thousands",
        ascending  = False
    )
)

        Model  Sales_Thousands powertrain_category
0     Corolla             1661             HEV,ICE
1        RAV4             1047        HEV,ICE,PHEV
2       Yaris              908             HEV,ICE
3       Camry              591             HEV,ICE
4       Hilux              580             HEV,ICE
5  Highlander              323         BEV,HEV,ICE
6      Sienna              278             HEV,ICE
7      Tacoma              257             HEV,ICE
8    Lexus RX              224                 NaN
9      Innova              210                 NaN

In [31]:
major_model_sales["Electrified_Available"] = (
    major_model_sales["powertrain_category"]
    .notna()
)

electrified_available_sales = major_model_sales.loc[
    major_model_sales["Electrified_Available"],
    "Sales_Thousands"
].sum()

total_major_model_sales = major_model_sales["Sales_Thousands"].sum()

share = (
    electrified_available_sales /
    total_major_model_sales * 100
)

print(
    f"Sales from model with electrified configuration: "
    f"{electrified_available_sales:,} thousand"
)

print(
    f"Share of 10 major-model sales: {share:.2f}%"
)

Sales from model with electrified configuration: 5,645 thousand
Share of 10 major-model sales: 92.86%

In [32]:
major_model_sales["Electrified_Available"] = (
    major_model_sales["powertrain_category"]
    .notna()
)

electrified_available_sales = major_model_sales.loc[
    major_model_sales["Electrified_Available"],
    "Sales_Thousands"
].sum()

total_major_model_sales = major_model_sales["Sales_Thousands"].sum()

share = (
    electrified_available_sales /
    total_major_model_sales * 100
)

print(
    f"Sales from models with electrified configurations: "
    f"{electrified_available_sales:,} thousand"
)

print(
    f"Share of 10 major-model sales: {share:.2f}%"
)

Sales from models with electrified configurations: 5,645 thousand
Share of 10 major-model sales: 92.86%

In [35]:
regional_2025_comparison = regional_2025[
    ["Region", "Sales"]
].merge(
    regional_electrified[
        (regional_electrified["Year"] == 2025) &
        (regional_electrified["Region"].isin(
            ["North America", "Europe", "Asia (Excluding China)", "China"]
        ))
    ],
    on="Region",
    how="left"
)

display(regional_2025_comparison)

          Region      Sales    Year  Electrified_Sales
0           Asia  3285605.0     NaN                NaN
1  North America  2929660.0  2025.0          1363916.0
2          Japan  1501263.0     NaN                NaN
3         Europe  1182551.0  2025.0           913797.0
4    Middle East   600891.0     NaN                NaN
5  Latin America   472049.0     NaN                NaN
6        Oceania   300560.0     NaN                NaN
7         Africa   264228.0     NaN                NaN
8         Others        NaN     NaN                NaN

In [39]:
sales_2025 = regional_sales[
    regional_sales["Year"] == 2025
].copy()

electrified_2025 = regional_electrified[
    regional_electrified["Year"] == 2025
].copy()

regional_electrification_2025 = pd.DataFrame({
    "Region": [
        "North America",
        "Europe",
        "Asia"
    ],
    "Total_Sales": [
        sales_2025.loc[
            sales_2025["Region"] == "North America", "Sales"
        ].iloc[0],

        sales_2025.loc[
            sales_2025["Region"] == "Europe", "Sales"
        ].iloc[0],

        sales_2025.loc[
            sales_2025["Region"] == "Asia", "Sales"
        ].iloc[0],

    ],
    "Electrified_Sales": [
        electrified_2025.loc[
            electrified_2025["Region"] == "North America",
        "Electrified_Sales"
        ].iloc[0],
        (
            electrified_2025.loc[
                electrified_2025["Region"] == "China",
                "Electrified_Sales"
            ].iloc[0]
            +
            electrified_2025.loc[
                electrified_2025["Region"] == "Asia (Excluding China)",
                "Electrified_Sales"
            ].iloc[0]
        )
    ]  
})

regional_electrification_2025["Electrification_Rate_%"]= (
    regional_electrification_2025["Electrified_Sales"]
    / regional_electrification_2025["Total_Sales"]
    * 100
)

display(
    regional_electrification_2025.round(2)
)

ValueError: All arrays must be of the same length

In [40]:
# 2025 total sales
sales_2025 = regional_sales[
    regional_sales["Year"] == 2025
].copy()

# Get electrified sales for 2025
electrified_2025 = regional_electrified[
    regional_electrified["Year"] == 2025
].copy()

# Build comparison table
regional_electrification_2025 = pd.DataFrame({
    "Region": [
        "North America",
        "Europe",
        "Asia"
    ],
    "Total_Sales": [
        sales_2025.loc[
            sales_2025["Region"] == "North America", "Sales"
        ].iloc[0],

        sales_2025.loc[
            sales_2025["Region"] == "Europe", "Sales"
        ].iloc[0],

        sales_2025.loc[
            sales_2025["Region"] == "Asia", "Sales"
        ].iloc[0]
    ],
    "Electrified_Sales": [
        electrified_2025.loc[
            electrified_2025["Region"] == "North America",
            "Electrified_Sales"
        ].iloc[0],

        electrified_2025.loc[
            electrified_2025["Region"] == "Europe",
            "Electrified_Sales"
        ].iloc[0],

        (
            electrified_2025.loc[
                electrified_2025["Region"] == "China",
                "Electrified_Sales"
            ].iloc[0]
            +
            electrified_2025.loc[
                electrified_2025["Region"] == "Asia (Excluding China)",
                "Electrified_Sales"
            ].iloc[0]
        )
    ]
})

regional_electrification_2025["Electrification_Rate_%"] = (
    regional_electrification_2025["Electrified_Sales"]
    / regional_electrification_2025["Total_Sales"]
    * 100
)

display(
    regional_electrification_2025.round(2)
)

          Region  Total_Sales  Electrified_Sales  Electrification_Rate_%
0  North America    2929660.0          1363916.0                   46.56
1         Europe    1182551.0           913797.0                   77.27
2           Asia    3285605.0          1381871.0                   42.06

In [41]:
regional_h1_2026_comparison = pd.DataFrame({
    "Region": [
        "Japan",
        "North America",
        "Europe",
        "Asia Excluding China",
        "China"
    ],
    "Sales_H1_2025": [
        768445,
        1438981,
        612007,
        706267,
        837744
    ],
    "Sales_H1_2026": [
        804721,
        1452343,
        612271,
        741384,
        694670
    ],
    "Electrified_H1_2025": [
        480868,
        700971,
        475108,
        184165,
        438504
    ],
    "Electrified_H1_2026": [
        499615,
        793726,
        533389,
        239618,
        439939
    ]
})

regional_h1_2026_comparison["Sales_YoY_%"] = (
    (regional_h1_2026_comparison["Sales_H1_2026"] /
     regional_h1_2026_comparison["Sales_H1_2025"]) - 1
) * 100

regional_h1_2026_comparison["Electrified_YoY_%"] = (
    (regional_h1_2026_comparison["Electrified_H1_2026"] /
     regional_h1_2026_comparison["Electrified_H1_2025"]) - 1
) * 100

regional_h1_2026_comparison["Electrification_Rate_2026_%"] = (
    regional_h1_2026_comparison["Electrified_H1_2026"] /
    regional_h1_2026_comparison["Sales_H1_2026"] * 100
)

display(
    regional_h1_2026_comparison.round(2)
)

,Region,Sales_H1_2025,Sales_H1_2026,Electrified_H1_2025,Electrified_H1_2026,Sales_YoY_%,Electrified_YoY_%,Electrification_Rate_2026_%
0,Japan,768445,804721,480868,499615,4.72,3.90,62.09
1,North America,1438981,1452343,700971,793726,0.93,13.23,54.65
2,Europe,612007,612271,475108,533389,0.04,12.27,87.12
3,Asia Excluding China,706267,741384,184165,239618,4.97,30.11,32.32
4,China,837744,694670,438504,439939,-17.08,0.33,63.33

In [42]:
 powertrain_h1_2026 = electrified_sales[
    electrified_sales["Powertrain"] != "Total"
 ].copy()
powertrain_h1_2026 = powertrain_h1_2026[
    powertrain_h1_2026["Year"].isin([2025,2026])
]

display(powertrain_h1_2026)

    Year Powertrain      Sales
9   2025        HEV  4433503.0
19  2025       MHEV   177152.0
29  2025       PHEV   183845.0
39  2025       FCEV     1257.0
49  2025        BEV   199137.0

In [43]:
powertrain_h1_comparison = pd.DataFrame({
    "Powertrain": [
        "HEV",
        "MHEV",
        "PHEV",
        "FCEV",
        "BEV"
    ],
    "H1_2025": [
        2233075,
        73672,
        92931,
        492,
        82085
    ],
    "H1_2026": [
        2330877,
        87465,
        95428,
        360,
        193172
    ]
})

powertrain_h1_comparison["YoY_%"] = (
    (
        powertrain_h1_comparison["H1_2026"]
        / powertrain_h1_comparison["H1_2025"]
    ) - 1
) * 100

display(
    powertrain_h1_comparison.round(2)
)

  Powertrain  H1_2025  H1_2026   YoY_%
0        HEV  2233075  2330877    4.38
1       MHEV    73672    87465   18.72
2       PHEV    92931    95428    2.69
3       FCEV      492      360  -26.83
4        BEV    82085   193172  135.33

In [46]:
powertrain_h1_comparison["Absolute_Change"] = (
    powertrain_h1_comparison["H1_2026"]
    - powertrain_h1_comparison["H1_2025"]
)

total_change  = powertrain_h1_comparison["Absolute_Change"].sum()

powertrain_h1_comparison["Contribution_to_Growth_%"] = (
    powertrain_h1_comparison["Absolute_Change"]
    / total_change
) * 100

display(
    powertrain_h1_comparison.round(2)
)

,Powertrain,H1_2025,H1_2026,YoY_%,Absolute_Change,Contribution_to_Growth_%
0,HEV,2233075,2330877,4.38,97802,43.46
1,MHEV,73672,87465,18.72,13793,6.13
2,PHEV,92931,95428,2.69,2497,1.11
3,FCEV,492,360,-26.83,-132,-0.06
4,BEV,82085,193172,135.33,111087,49.36