In [1]:
import pandas as pd

In [3]:
toyota = pd.read_excel("toyota.xlsx")
print("Shape:", toyota.shape)
print("\nColumns:")
print(toyota.columns.tolist())
display(toyota.head())

Shape: (1047, 23)

Columns:
['make_group', 'make', 'model', 'generation', 'gen_year_start', 'gen_year_end', 'body_type', 'engine_label', 'fuel_type', 'cylinders', 'displacement_cc', 'power_hp', 'torque_nm', 'transmission', 'drivetrain', 'zero_to_100_s', 'top_speed_kmh', 'fuel_economy_combined_l100', 'length_mm', 'width_mm', 'height_mm', 'wheelbase_mm', 'curb_weight_kg']

,make_group,make,model,generation,gen_year_start,gen_year_end,body_type,engine_label,fuel_type,cylinders,...,transmission,drivetrain,zero_to_100_s,top_speed_kmh,fuel_economy_combined_l100,length_mm,width_mm,height_mm,wheelbase_mm,curb_weight_kg
0,toyota,Toyota,4Runner,4Runner (2024),2024,NaN,NaN,2.4L (282 HP),Gasoline,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,toyota,Toyota,4Runner,4Runner (2013),2013,2024.0,NaN,4.0L V6 5AT 274 HP (4x2),Gasoline,6.0,...,5-speed automatic,Rear Wheel Drive,NaN,NaN,12.4,4831.0,1925.0,1816.0,2789.0,1996.0
2,toyota,Toyota,4Runner,4Runner (2013),2013,2024.0,NaN,4.0L V6 5AT 274 HP (4x4),Gasoline,6.0,...,5-speed automatic,All Wheel Drive,NaN,NaN,13.1,4831.0,1925.0,1816.0,2789.0,2121.0
3,toyota,Toyota,4Runner,4Runner (2009),2009,2013.0,NaN,2.7L 4AT RWD (157 HP),Gasoline,4.0,...,4-speed automatic,Rear Wheel Drive,NaN,NaN,11.8,4823.0,1925.0,1816.0,2789.0,1948.0
4,toyota,Toyota,4Runner,4Runner (2009),2009,2013.0,NaN,4.0L V6 5AT AWD (274 HP),Gasoline,6.0,...,5-speed Electronically Controlled automatic Tr...,Rear Wheel Drive,NaN,NaN,12.4,4823.0,1925.0,1816.0,2789.0,2121.0

In [7]:
missing_summary = pd.DataFrame({
    "Missing_Count": toyota.isna().sum(),
    "Missing_%": toyota.isna().mean() * 100
})

display(
    missing_summary.sort_values(
        "Missing_%",
        ascending=False
    ).round(2)
)

                            Missing_Count  Missing_%
body_type                            1047     100.00
top_speed_kmh                         352      33.62
zero_to_100_s                         342      32.66
fuel_economy_combined_l100            205      19.58
curb_weight_kg                        123      11.75
gen_year_end                           99       9.46
displacement_cc                        44       4.20
torque_nm                              41       3.92
cylinders                              27       2.58
transmission                           26       2.48
wheelbase_mm                           21       2.01
height_mm                              17       1.62
length_mm                              17       1.62
width_mm                               17       1.62
drivetrain                              7       0.67
power_hp                                7       0.67
fuel_type                               1       0.10
generation                              0       0.00
model                                   0       0.00
make_group                              0       0.00
gen_year_start                          0       0.00
make                                    0       0.00
engine_label                            0       0.00

In [8]:
toyota[toyota["fuel_type"].isna()]

,make_group,make,model,generation,gen_year_start,gen_year_end,body_type,engine_label,fuel_type,cylinders,...,transmission,drivetrain,zero_to_100_s,top_speed_kmh,fuel_economy_combined_l100,length_mm,width_mm,height_mm,wheelbase_mm,curb_weight_kg
825,toyota,Toyota,Sequoia,Sequoia (2022),2022,NaN,NaN,V6 i-FORCE MAX 10T AWD (437 HP),NaN,6.0,...,10-speed automatic,All Wheel Drive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
toyota_2016 = toyota[
    (toyota["gen_year_end"].isna()) |
    (toyota["gen_year_end"] >= 2016)
].copy()

print("Original shape:", toyota.shape)
print("2016+ shape:", toyota_2016.shape)

display(toyota_2016.head())

Original shape: (1047, 23)
2016+ shape: (385, 23)

,make_group,make,model,generation,gen_year_start,gen_year_end,body_type,engine_label,fuel_type,cylinders,...,transmission,drivetrain,zero_to_100_s,top_speed_kmh,fuel_economy_combined_l100,length_mm,width_mm,height_mm,wheelbase_mm,curb_weight_kg
0,toyota,Toyota,4Runner,4Runner (2024),2024,NaN,NaN,2.4L (282 HP),Gasoline,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,toyota,Toyota,4Runner,4Runner (2013),2013,2024.0,NaN,4.0L V6 5AT 274 HP (4x2),Gasoline,6.0,...,5-speed automatic,Rear Wheel Drive,NaN,NaN,12.4,4831.0,1925.0,1816.0,2789.0,1996.0
2,toyota,Toyota,4Runner,4Runner (2013),2013,2024.0,NaN,4.0L V6 5AT 274 HP (4x4),Gasoline,6.0,...,5-speed automatic,All Wheel Drive,NaN,NaN,13.1,4831.0,1925.0,1816.0,2789.0,2121.0
17,toyota,Toyota,Agya,Agya (2012),2012,2017.0,NaN,1.0L 4AT (65 HP),Gasoline,3.0,...,4 speed automatic,Front Wheel Drive,NaN,NaN,NaN,3599.0,1600.0,1519.0,2451.0,NaN
18,toyota,Toyota,Agya,Agya (2012),2012,2017.0,NaN,1.0L 5MT (65 HP),Gasoline,3.0,...,5 speed manual,Front Wheel Drive,NaN,NaN,NaN,3599.0,1600.0,1519.0,2451.0,NaN

In [12]:
toyota_2016 = toyota_2016.drop(columns=["body_type"])

print("Shape:", toyota_2016.shape)
print("Columns:", toyota_2016.columns.tolist())

Shape: (385, 22)
Columns: ['make_group', 'make', 'model', 'generation', 'gen_year_start', 'gen_year_end', 'engine_label', 'fuel_type', 'cylinders', 'displacement_cc', 'power_hp', 'torque_nm', 'transmission', 'drivetrain', 'zero_to_100_s', 'top_speed_kmh', 'fuel_economy_combined_l100', 'length_mm', 'width_mm', 'height_mm', 'wheelbase_mm', 'curb_weight_kg']

In [13]:
print("Exact duplicate rows:", toyota_2016.duplicated().sum())

Exact duplicate rows: 0

In [14]:
toyota_2016.dtypes

make_group                     object
make                           object
model                          object
generation                     object
gen_year_start                  int64
gen_year_end                  float64
engine_label                   object
fuel_type                      object
cylinders                     float64
displacement_cc               float64
power_hp                      float64
torque_nm                     float64
transmission                   object
drivetrain                     object
zero_to_100_s                 float64
top_speed_kmh                 float64
fuel_economy_combined_l100    float64
length_mm                     float64
width_mm                      float64
height_mm                     float64
wheelbase_mm                  float64
curb_weight_kg                float64
dtype: object

In [15]:
toyota_2016.info()

<class 'pandas.core.frame.DataFrame'>
Index: 385 entries, 0 to 1037
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   make_group                  385 non-null    object
 1   make                        385 non-null    object
 2   model                       385 non-null    object
 3   generation                  385 non-null    object
 4   gen_year_start              385 non-null    int64
 5   gen_year_end                286 non-null    float64
 6   engine_label                385 non-null    object
 7   fuel_type                   384 non-null    object
 8   cylinders                   358 non-null    float64
 9   displacement_cc             341 non-null    float64
 10  power_hp                    379 non-null    float64
 11  torque_nm                   345 non-null    float64
 12  transmission                359 non-null    object
 13  drivetrain                  378 non-null    object
 14  zero_to_100_s               179 non-null    float64
 15  top_speed_kmh               154 non-null    float64
 16  fuel_economy_combined_l100  271 non-null    float64
 17  length_mm                   368 non-null    float64
 18  width_mm                    368 non-null    float64
 19  height_mm                   368 non-null    float64
 20  wheelbase_mm                365 non-null    float64
 21  curb_weight_kg              270 non-null    float64
dtypes: float64(13), int64(1), object(8)
memory usage: 69.2+ KB

In [16]:
toyota_2016[toyota_2016["fuel_type"].isna()][
    ["model", "generation", "gen_year_start", "gen_year_end", "engine_label"]
]

,model,generation,gen_year_start,gen_year_end,engine_label
825,Sequoia,Sequoia (2022),2022,NaN,V6 i-FORCE MAX 10T AWD (437 HP)

In [19]:
toyota_2016.loc[
    (toyota_2016["model"] == "Sequoia") &
    (toyota_2016["generation"] == "Sequoia (2022)") &
    (toyota_2016["fuel_type"].isna()),
    "fuel_type"
] = "Hybrid Gasoline"

In [20]:
print("Missing fuel_type", toyota_2016["fuel_type"].isna().sum())

display(
     toyota_2016[toyota_2016["model"] == "Sequoia"][
        ["model", "generation", "gen_year_start", "gen_year_end",
         "engine_label", "fuel_type"]
    ]
)

Missing fuel_type 0

,model,generation,gen_year_start,gen_year_end,engine_label,fuel_type
825,Sequoia,Sequoia (2022),2022,NaN,V6 i-FORCE MAX 10T AWD (437 HP),Hybrid Gasoline
826,Sequoia,Sequoia (2019),2019,2022.0,5.7L V8 VVT-i 6AT (381 HP),Gasoline
827,Sequoia,Sequoia (2019),2019,2022.0,5.7L V8 VVT-i 6AT AWD (381 HP),Gasoline
828,Sequoia,Sequoia (2017),2017,2022.0,5.7L V8 6AT AWD (381 HP),Gasoline
829,Sequoia,Sequoia (2017),2017,2022.0,5.7L V8 6AT RWD (381 HP),Gasoline
830,Sequoia,Sequoia (2007),2007,2017.0,4.6L V8 AWD 6AT (310 HP),Gasoline
831,Sequoia,Sequoia (2007),2007,2017.0,4.6L V8 RWD 6AT (310 HP),Gasoline
832,Sequoia,Sequoia (2007),2007,2017.0,4.7L V8 AWD 5AT (273 HP),Gasoline
833,Sequoia,Sequoia (2007),2007,2017.0,4.7L V8 RWD 5AT (273 HP),Gasoline
834,Sequoia,Sequoia (2007),2007,2017.0,5.7L V8 AWD 6AT (381 HP),Gasoline
835,Sequoia,Sequoia (2007),2007,2017.0,5.7L V8 RWD 6AT (381 HP),Gasoline

In [21]:
toyota_2016.isnull().sum()

make_group                      0
make                            0
model                           0
generation                      0
gen_year_start                  0
gen_year_end                   99
engine_label                    0
fuel_type                       0
cylinders                      27
displacement_cc                44
power_hp                        6
torque_nm                      40
transmission                   26
drivetrain                      7
zero_to_100_s                 206
top_speed_kmh                 231
fuel_economy_combined_l100    114
length_mm                      17
width_mm                       17
height_mm                      17
wheelbase_mm                   20
curb_weight_kg                115
dtype: int64

In [23]:
columns_to_drop = [
    "zero_to_100_s",
    "top_speed_kmh"
]
toyota_clean = toyota_2016.drop(columns = columns_to_drop).copy()
print("Shape:", toyota_clean.shape)
print("\nMissing values:")
print(toyota_clean.isna().sum())

Shape: (385, 20)

Missing values:
make_group                      0
make                            0
model                           0
generation                      0
gen_year_start                  0
gen_year_end                   99
engine_label                    0
fuel_type                       0
cylinders                      27
displacement_cc                44
power_hp                        6
torque_nm                      40
transmission                   26
drivetrain                      7
fuel_economy_combined_l100    114
length_mm                      17
width_mm                       17
height_mm                      17
wheelbase_mm                   20
curb_weight_kg                115
dtype: int64

In [24]:
toyota_clean["fuel_type"].value_counts()

fuel_type
Gasoline              208
Hybrid Gasoline        57
Diesel                 55
Hybrid                 33
Electric               21
Plug-in Hybrid          5
Mild Hybrid             4
Hybrid Diesel           1
Mild Hybrid Diesel      1
Name: count, dtype: int64

In [26]:
fuel_mapping = {
    "Gasoline": "ICE",
    "Diesel": "ICE",
    "Hybrid Gasoline": "HEV",
    "Hybrid": "HEV",
    "Hybrid Diesel": "HEV",
    "Plug-in Hybrid": "PHEV",
    "Electric": "BEV",
    "Mild Hybrid": "MHEV",
    "Mild Hybrid Diesel": "MHEV",
    
}
toyota_clean["powertrain_category"] = toyota_clean["fuel_type"].map(fuel_mapping)
print(toyota_clean["powertrain_category"].value_counts())

powertrain_category
ICE     263
HEV      91
BEV      21
PHEV      5
MHEV      5
Name: count, dtype: int64

In [27]:
print(
    "Unmapped fuel types:",
    toyota_clean.loc[
    toyota_clean["powertrain_category"].isna(),
    "fuel_type"
    ].unique()
)

Unmapped fuel types: []

In [28]:
toyota_clean.describe().T

,count,mean,std,min,25%,50%,75%,max
gen_year_start,385.0,2017.509091,4.345202,2007.0,2015.00,2017.0,2020.00,2026.0
gen_year_end,286.0,2019.748252,2.859195,2016.0,2017.00,2019.0,2022.00,2026.0
cylinders,358.0,4.500000,1.285014,3.0,4.00,4.0,4.00,8.0
displacement_cc,341.0,2418.510264,1136.303555,996.0,1598.00,1995.0,2755.00,5663.0
power_hp,379.0,185.727704,86.398838,65.0,116.00,166.0,234.00,437.0
torque_nm,345.0,265.211594,136.336489,0.0,160.00,212.0,362.00,790.0
fuel_economy_combined_l100,271.0,7.227675,3.923256,0.0,4.65,6.5,8.50,31.8
length_mm,368.0,4683.301630,483.648891,3454.0,4361.00,4651.0,4933.25,5933.0
width_mm,368.0,1837.595109,108.827397,1600.0,1775.00,1826.0,1871.75,2570.0
height_mm,368.0,1619.875000,169.425671,1285.0,1471.00,1595.0,1793.00,1981.0
wheelbase_mm,365.0,2798.243836,283.295526,2339.0,2639.00,2700.0,2850.00,3701.0
curb_weight_kg,270.0,1643.537037,538.968391,840.0,1276.00,1509.0,1942.00,4445.0

In [30]:
print("Torque = 0:")
display(
    toyota_clean[toyota_clean["torque_nm"] == 0][
        ["model", "generation", "engine_label", "fuel_type", "power_hp", "torque_nm"]
    ]
)

print("\nFuel economy = 0:")
display(
    toyota_clean[toyota_clean["fuel_economy_combined_l100"] == 0][
        ["model", "generation", "engine_label", "fuel_type",
         "fuel_economy_combined_l100"]
    ]
)

Torque = 0:

     model     generation         engine_label fuel_type  power_hp  torque_nm
85  Avalon  Avalon (2018)  2.5 L4 6AT (200 HP)    Hybrid     200.0        0.0

Fuel economy = 0:

,model,generation,engine_label,fuel_type,fuel_economy_combined_l100
633,Hilux,Hilux Double Cab (2015),2.7L 6AT 2WD (166 HP),Gasoline,0.0
634,Hilux,Hilux Double Cab (2015),4.0L V6 6AT 2WD (238 HP),Gasoline,0.0
637,Hilux,Hilux Double Cab (2015),2.8L 6AT 2WD (170 HP),Diesel,0.0
638,Hilux,Hilux Double Cab (2015),2.8L 6AT 4WD (177 HP),Diesel,0.0
639,Hilux,Hilux Double Cab (2015),2.8L 6MT 2WD (170 HP),Diesel,0.0
640,Hilux,Hilux Double Cab (2015),2.8L 6MT 4WD (177 HP),Diesel,0.0

In [31]:
toyota_clean.loc[
    toyota_clean["model"].eq("Avalon") &
    toyota_clean["generation"].eq("Avalon (2018)") &
    toyota_clean["torque_nm"].eq(0),
    "torque_nm"
] = 212

In [32]:
toyota_clean[
    (toyota_clean["model"] == "Avalon") &
    (toyota_clean["generation"] == "Avalon (2018)")

][
    ["model", "generation", "engine_label",
     "fuel_type", "power_hp", "torque_nm"]
]

,model,generation,engine_label,fuel_type,power_hp,torque_nm
84,Avalon,Avalon (2018),3.5 V6 6AT (268 HP) FWD,Gasoline,268.0,336.0
85,Avalon,Avalon (2018),2.5 L4 6AT (200 HP),Hybrid,200.0,212.0

In [33]:
hilux_fuel_economy = {
    "2.7L 6AT 2WD (166 HP)": 10.6,
    "4.0L V6 6AT 2WD (238 HP)": 11.7,
    "2.8L 6AT 2WD (170 HP)": 8.0,
    "2.8L 6AT 4WD (177 HP)": 8.5,
    "2.8L 6MT 2WD (170 HP)": 7.6,
    "2.8L 6MT 4WD (177 HP)": 7.6
}

mask = (
    (toyota_clean["model"] == "Hilux") &
    (toyota_clean["fuel_economy_combined_l100"] == 0)
)

toyota_clean.loc[mask, "fuel_economy_combined_l100"] = (
    toyota_clean.loc[mask, "engine_label"].map(hilux_fuel_economy)
)

In [34]:
toyota_clean.loc[
    (toyota_clean["model"] == "Hilux") &
    toyota_clean["engine_label"].isin(hilux_fuel_economy),
    ["model", "generation", "engine_label",
     "fuel_type", "fuel_economy_combined_l100"]
]

,model,generation,engine_label,fuel_type,fuel_economy_combined_l100
633,Hilux,Hilux Double Cab (2015),2.7L 6AT 2WD (166 HP),Gasoline,10.6
634,Hilux,Hilux Double Cab (2015),4.0L V6 6AT 2WD (238 HP),Gasoline,11.7
637,Hilux,Hilux Double Cab (2015),2.8L 6AT 2WD (170 HP),Diesel,8.0
638,Hilux,Hilux Double Cab (2015),2.8L 6AT 4WD (177 HP),Diesel,8.5
639,Hilux,Hilux Double Cab (2015),2.8L 6MT 2WD (170 HP),Diesel,7.6
640,Hilux,Hilux Double Cab (2015),2.8L 6MT 4WD (177 HP),Diesel,7.6

In [35]:
numeric_cols = toyota_clean.select_dtypes(include="number").columns

zero_counts = (toyota_clean[numeric_cols] == 0).sum()

display(zero_counts[zero_counts > 0])

Series([], dtype: int64)

In [36]:
missing_summary = pd.DataFrame({
    "Missing_Count": toyota_clean.isna().sum(),
    "Missing_%": toyota_clean.isna().mean() * 100
})

display(
    missing_summary[missing_summary["Missing_Count"] > 0]
    .sort_values("Missing_%", ascending=False)
    .round(2)
)

                            Missing_Count  Missing_%
curb_weight_kg                        115      29.87
fuel_economy_combined_l100            114      29.61
gen_year_end                           99      25.71
displacement_cc                        44      11.43
torque_nm                              40      10.39
cylinders                              27       7.01
transmission                           26       6.75
wheelbase_mm                           20       5.19
height_mm                              17       4.42
width_mm                               17       4.42
length_mm                              17       4.42
drivetrain                              7       1.82
power_hp                                6       1.56

In [37]:
toyota_clean.to_excel("toyota_clean.xlsx", index=False)

print("Saved successfully!")
print("Shape:", toyota_clean.shape)

Saved successfully!
Shape: (385, 21)

In [38]:
toyota_clean.head()

,make_group,make,model,generation,gen_year_start,gen_year_end,engine_label,fuel_type,cylinders,displacement_cc,...,torque_nm,transmission,drivetrain,fuel_economy_combined_l100,length_mm,width_mm,height_mm,wheelbase_mm,curb_weight_kg,powertrain_category
0,toyota,Toyota,4Runner,4Runner (2024),2024,NaN,2.4L (282 HP),Gasoline,4.0,NaN,...,430.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICE
1,toyota,Toyota,4Runner,4Runner (2013),2013,2024.0,4.0L V6 5AT 274 HP (4x2),Gasoline,6.0,3956.0,...,377.0,5-speed automatic,Rear Wheel Drive,12.4,4831.0,1925.0,1816.0,2789.0,1996.0,ICE
2,toyota,Toyota,4Runner,4Runner (2013),2013,2024.0,4.0L V6 5AT 274 HP (4x4),Gasoline,6.0,3956.0,...,377.0,5-speed automatic,All Wheel Drive,13.1,4831.0,1925.0,1816.0,2789.0,2121.0,ICE
17,toyota,Toyota,Agya,Agya (2012),2012,2017.0,1.0L 4AT (65 HP),Gasoline,3.0,998.0,...,91.0,4 speed automatic,Front Wheel Drive,NaN,3599.0,1600.0,1519.0,2451.0,NaN,ICE
18,toyota,Toyota,Agya,Agya (2012),2012,2017.0,1.0L 5MT (65 HP),Gasoline,3.0,998.0,...,91.0,5 speed manual,Front Wheel Drive,NaN,3599.0,1600.0,1519.0,2451.0,NaN,ICE